### ISSUE TITLE
key [SETTINGS] doesn't exist (existing keys:production)

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1395]
Reproducible [here](http://salty-castle-1872.herokuapp.com/)

I've gotten this error a few times while using Railo-Express but also get it while working with Heroku / Dokku instances. Can anyone point me in a direction to start debugging? This is a current sticking point for us.

Initially thought it was rewrite rules, but they seem to be working. It just simply looks like a problem with the settings.ini file somehow.  Currently it's a clean install of Mura at the URL.

**Comment by Bilal-S** [comment]
This seems to happen on some "*nix" environments. For example, it just happened to me on Amazon Linux. I copied a newly generated settings.ini.cfm from windows into the instance and started up correctly.

Here is a newly created file setting.ini.cfm you can add to config directory:
```
[settings]
appname=Mura CMS
appreloadkey=appreload
installed=0
mode=production
[production]
accesscontrolheaders=false
accesscontrolcredentials=false
admindomain=
adminemail=
adminssl=0
allowautoupdates=1
allowlocalfiles=false
assetdir=
assetpath=
autodiscoverplugins=false
autopreviewimages=true
autoresetpasswords=true
autoupdatemode=default
bcryptlogrounds=10
bcryptpasswords=true
bcryptreseedfrequency=60
clientmanagement=false
clientstorage=
confirmsaveasdraft=true
context=
customtagpaths=
dashboard=true
dashboardcomments=true
datacollection=true
datasource=
dbcasesensitive=false
dbpassword=
dbtype=
dbtablespace=USERS
dbusername=
debuggingenabled=true
defaultfilemode=777
donottrackagents=
editablecomments=0
enablemuratag=true
errortemplate=/muraWRM/config/error.html
filedir=
filestore=filedir
fmshowapplicationroot=1
fmshowsitefiles=1
forceadminssl=true
hashurls=false
haslockablenodes=false
imageinterpolation=highestQuality
indexfileinurls=1
javaenabled=true
javasettingsloadcoldfusionclasspath=true
javasettingsreloadonchage=false
javasettingswatchextensions=jar,class
javasettingswatchinterval=60
locale=Server
logevents=0
loginstrikes=4
mailserverip=
mailserverpassword=
mailserverpopport=110
mailserversmtpport=25
mailserverssl=false
mailservertls=false
mailserverusername=
mapdir=mura
maxarchivedversions=50
maxportalitems=1000
maxsourceimagewidth=4000
notifywithversionlink=true
ormautomanagesession=false
ormcfclocation=
ormdatasource=
ormdbcreate=update
ormenabled=true
ormeventhandling=true
ormflushatrequestend=false
ormlogsql=false
ormsavemapping=false
ormskipcfcwitherror=false
ormusedbformapping=true
ping=0
plugindir=
port=${cgi.SERVER_PORT}
proxypassword=
proxyport=${cgi.SERVER_PORT}
proxyserver=
proxyuser=
purgedrafts=true
recaptchasitekey=
recaptchasecret=
recaptchalanguage=en
rendermuraalerts=true
requesttimeout=1000
s3accesskeyid=
s3awssecretkey=
sameformfieldsasarray=false
scriptprotect=true
scriptprotectexceptions=Body
securecookies=false
sendfrommailserverusername=true
sessionhistory=1
sessiontimeout=180
sharableremotesessions=1
showadminloginhelp=true
siteidinurls=false
sortpermission=editor
sourceimagescale=3000
sourceimagescaleby=x
strictextendeddata=1
strictfactory=true
strongpasswordregex=(?=^.{7,15}$)(?=.*\d)(?![.\n])(?=.*[a-zA-Z]).*$
strongpasswords=0
stub=
tempdir=
title=Mura CMS
tracksessioninnewthread=1
usedefaultsmtpserver=1
usefilemode=false
uselegacysessions=0
webrootmap=muraWRM
windowdocumentdomain=
```

**Comment by al3x-edge** [comment]
Now getting these issues with Mura 7 without changing the install process from what we've been doing.  The top settings section is missing for some reason, but upon adding the new options (don't normally have to do this) the install finishes to the next screen, but then immediately bails out on `key [MAPDIR] doesn't exist` after clicking the finish install button.

```
key [MAPDIR] doesn't exist 

Code: 0 

Type: expression 

			
				key [MAPDIR] doesn't exist
	at lucee.runtime.type.util.StructSupport.invalidKey(StructSupport.java:66):66
	at lucee.runtime.type.StructImpl.get(StructImpl.java:120):120
	at lucee.runtime.type.util.StructSupport.get(StructSupport.java:237):237
	at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:255):255
	at lucee.runtime.PageContextImpl.get(PageContextImpl.java:1436):1436
	at config.appcfc.onapplicationstart_include_cfm$cf.call(/var/www/mura7preview.fh-group.com/config/appcfc/onApplicationStart_include.cfm:142):142
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:855):855
	at config.appcfc.onrequeststart_include_cfm$cf.call(/var/www/mura7preview.fh-group.com/config/appcfc/onRequestStart_include.cfm:106):106
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:855):855
	at admin.application_cfc$cf.udfCall(/var/www/mura7preview.fh-group.com/admin/Application.cfc:165):165
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:405):405
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:131):131
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:35):35
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2262):2262
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2225):2225
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727):727
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303):303
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220):220
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122):122
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501):501
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170):170
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116):116
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683):683
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041):1041
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607):607
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313):313
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617
	at java.lang.Thread.run(Thread.java:745):745

			

Column: 0
ID: ??
Line: 142
Raw Trace: config.appcfc.onapplicationstart_include_cfm$cf.call(/var/www/mura7preview.fh-group.com/config/appcfc/onApplicationStart_include.cfm:142)
Template: /var/www/mura7preview.fh-group.com/config/appcfc/onApplicationStart_include.cfm
Type: cfml
```
