### ISSUE TITLE
Error Saving Main Site Settings Page

### ISSUE THREAD

**Issue by gozargozarian** [blueriver/MuraCMS#1766]
Mura Version 6.2
Railo 4.2.1.008
PostgreSQL 9.3
Java 1.7

Attempting to simply save the settings from the site settings page (/admin/?muraAction=cSettings.editSite&siteid=default).  I am using PostgreSQL 9.3 as the database.  I get an error that seems to be directly related to PostgreSQL handling of booleans in the database.  Error is on the usessl setting.

ERROR: column "usessl" is of type integer but expression is of type boolean

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1608):1608
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1343):1343
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:194):194
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:470):470
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:369):369
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:362):362
	at railo.runtime.db.driver.state.StateUtil.execute(StateUtil.java:127):127
	at railo.runtime.db.driver.state.StatePreparedStatement.execute(StatePreparedStatement.java:117):117
	at railo.runtime.type.util.QueryUtil.execute(QueryUtil.java:222):222
	at railo.runtime.type.QueryImpl.(QueryImpl.java:233):233
	at railo.runtime.tag.Query.executeDatasoure(Query.java:687):687
	at railo.runtime.tag.Query.doEndTag(Query.java:531):531
	at settings.settingsdao_cfc$cf.udfCall(/website/requirements/mura/settings/settingsDAO.cfc:373):373
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at settings.settingsmanager_cfc$cf.udfCall1(/website/requirements/mura/settings/settingsManager.cfc:241):241
	at settings.settingsmanager_cfc$cf.udfCall(/website/requirements/mura/settings/settingsManager.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at admin.core.controllers.csettings_cfc$cf.udfCall2(/website/admin/core/controllers/csettings.cfc:165):165
	at admin.core.controllers.csettings_cfc$cf.udfCall(/website/admin/core/controllers/csettings.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at admin.framework_cfc$cf.udfCall6(/website/admin/framework.cfc:1308):1308
	at admin.framework_cfc$cf.udfCall(/website/admin/framework.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at admin.framework_cfc$cf.udfCall2(/website/admin/framework.cfc:517):517
	at admin.framework_cfc$cf.udfCall(/website/admin/framework.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:388):388
	at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:204):204
	at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2212):2212
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2179):2179
	at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:331):331
	at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727):727
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303):303
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241):241
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220):220
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122):122
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503):503
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170):170
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103):103
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116):116
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421):421
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070):1070
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611):611
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314):314
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61
	at java.lang.Thread.run(Thread.java:745):745

Column: 0
ID: ??
Line: 373
Raw Trace: settings.settingsdao_cfc$cf.udfCall(/website/requirements/mura/settings/settingsDAO.cfc:373)
Template: /website/requirements/mura/settings/settingsDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 241
Raw Trace: settings.settingsmanager_cfc$cf.udfCall1(/website/requirements/mura/settings/settingsManager.cfc:241)
Template: /website/requirements/mura/settings/settingsManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 165
Raw Trace: admin.core.controllers.csettings_cfc$cf.udfCall2(/website/admin/core/controllers/csettings.cfc:165)
Template: /website/admin/core/controllers/csettings.cfc
Type: cfml

Column: 0
ID: ??
Line: 1308
Raw Trace: admin.framework_cfc$cf.udfCall6(/website/admin/framework.cfc:1308)
Template: /website/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 517
Raw Trace: admin.framework_cfc$cf.udfCall2(/website/admin/framework.cfc:517)
Template: /website/admin/framework.cfc
Type: cfml

**Comment by stevewithington** [comment]
I believe we've fixed this issue. Could you please update and retest?

**Comment by gozargozarian** [comment]
Yep.  That was it.  Didn't even think about updating because I used the download and install version that is in Railo's app control panel.  Thanks for that!

**Comment by stevewithington** [comment]
No problem. Closing as resolved.
