### ISSUE TITLE
Homepage broken after update to the 6.2 preview

### ISSUE THREAD

**Issue by MarcAckermann** [blueriver/MuraCMS#1772]
Mura Version 6.2.6145
Railo 4.2.1
MsSQL 12

The frontend homepage just returns this error. Reload and also server restart didn't fix it

500 Error
Can't cast String [] to a boolean
Code: 0
Type: 0

Can't cast String [] to a boolean
	at railo.runtime.op.Caster.toBooleanValue(Caster.java:313):313
	at railo.runtime.op.Caster.toBooleanValue(Caster.java:288):288
	at content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:810):810
	at content.contentserver_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1755):1755
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at content.contentrenderer_cfc$cf.udfCall6(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc:1563):1563
	at content.contentrenderer_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentrenderer_cfc$cf.udfCall9(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc:2902):2902
	at content.contentrenderer_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at _default.includes.themes.jpop2.templates.inc.footer_cfm$cf.call(D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\inc\footer.cfm:29):29
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:813):813
	at _default.includes.themes.jpop2.templates.jpop_home_cfm$cf.call(D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\jpop_home.cfm:325):325
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:813):813
	at translator.standardhtmltranslator_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\Translator\standardHTMLTranslator.cfc:91):91
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1755):1755
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:133):133
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at handler.standardeventshandler_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc:87):87
	at handler.standardeventshandler_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:89):89
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at handler.standardeventshandler_cfc$cf.udfCall3(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc:413):413
	at handler.standardeventshandler_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:89):89
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:764):764
	at content.contentserver_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:257):257
	at content.contentserver_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:307):307
	at content.contentserver_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:644):644
	at content.contentserver_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at index_cfm$cf.call(D:\httpdoc\wwwroot3\index.cfm:48):48
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:861):861
	at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:206):206
	at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2212):2212
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2179):2179
	at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:331):331
	at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728):728
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222):222
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123):123
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472):472
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171):171
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99):99
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407):407
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589):589
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310):310
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source):-1
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source):-1
	at java.lang.Thread.run(Unknown Source):-1

Column: 0
ID: ??
Line: 810
Raw Trace: content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:810)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 1563
Raw Trace: content.contentrenderer_cfc$cf.udfCall6(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc:1563)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 2902
Raw Trace: content.contentrenderer_cfc$cf.udfCall9(D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc:2902)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 29
Raw Trace: _default.includes.themes.jpop2.templates.inc.footer_cfm$cf.call(D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\inc\footer.cfm:29)
Template: D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\inc\footer.cfm
Type: cfml

Column: 0
ID: ??
Line: 325
Raw Trace: _default.includes.themes.jpop2.templates.jpop_home_cfm$cf.call(D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\jpop_home.cfm:325)
Template: D:\httpdoc\wwwroot3\default\includes\themes\jpop2\templates\jpop_home.cfm
Type: cfml

Column: 0
ID: ??
Line: 91
Raw Trace: translator.standardhtmltranslator_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\Translator\standardHTMLTranslator.cfc:91)
Template: D:\httpdoc\wwwroot3\requirements\mura\Translator\standardHTMLTranslator.cfc
Type: cfml

Column: 0
ID: ??
Line: 133
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:133)
Template: D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 87
Raw Trace: handler.standardeventshandler_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc:87)
Template: D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 89
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:89)
Template: D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 413
Raw Trace: handler.standardeventshandler_cfc$cf.udfCall3(D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc:413)
Template: D:\httpdoc\wwwroot3\requirements\mura\Handler\standardEventsHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 89
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc:89)
Template: D:\httpdoc\wwwroot3\requirements\mura\plugin\pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 764
Raw Trace: content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:764)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 257
Raw Trace: content.contentserver_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:257)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 307
Raw Trace: content.contentserver_cfc$cf.udfCall1(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:307)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 644
Raw Trace: content.contentserver_cfc$cf.udfCall2(D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc:644)
Template: D:\httpdoc\wwwroot3\requirements\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 48
Raw Trace: index_cfm$cf.call(D:\httpdoc\wwwroot3\index.cfm:48)
Template: D:\httpdoc\wwwroot3\index.cfm
Type: cfml

**Comment by stevewithington** [comment]
@MarcAckermann in your `/config/settings.ini.cfm` file, do you have a setting for **siteidinurls**?

**Comment by stevewithington** [comment]
@MarcAckermann you may also want to try to login to your Railo Administrator, and clear the template cache.

**Comment by MarcAckermann** [comment]
Just updatetd to the lastest version and it looks fine now.

**Comment by MarcAckermann** [comment]
This is very odd. I did a few clicks on the page and now the error is back. I will try if I can reproduce it somehow.

**Comment by MarcAckermann** [comment]
application.contentRenderer.getCurrentURL() in my template code was the reson for this error

**Comment by stevewithington** [comment]
Thanks for letting us know. Cheers!
