### ISSUE TITLE
6.2 Update Error:  Can't cast String [] to a boolean

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1861]
Can't cast String [] to a boolean

Code: 0

Type: 0

Can't cast String [] to a boolean
	at railo.runtime.op.Caster.toBooleanValue(Caster.java:313):313
	at railo.runtime.op.Caster.toBooleanValue(Caster.java:288):288
	at content.contentrenderer_cfc$cf.udfCall6(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1644):1644
	at content.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:757):757
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at content.contentrenderer_cfc$cf.udfCall7(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1779):1779
	at content.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:757):757
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at content.contentrenderer_cfc$cf.udfCall5(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1105):1105
	at content.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:757):757
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at _default.includes.themes.cp.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc:159):159
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:757):757
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at _default.includes.themes.cp.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc:79):79
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at murascope_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/MuraScope.cfc:111):111
	at murascope_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/MuraScope.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:547):547
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:508):508
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1755):1755
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at _default.includes.themes.cp.templates.inc.header_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/inc/header.cfm:51):51
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:813):813
	at _default.includes.themes.cp.templates.three_column_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/three_column.cfm:4):4
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:813):813
	at _default.includes.themes.cp.templates.default_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/default.cfm:1):1
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:813):813
	at translator.standardhtmltranslator_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/Translator/standardHTMLTranslator.cfc:92):92
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1755):1755
	at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
	at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:133):133
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at handler.standardeventshandler_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc:87):87
	at handler.standardeventshandler_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:89):89
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at handler.standardeventshandler_cfc$cf.udfCall3(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc:409):409
	at handler.standardeventshandler_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751
	at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203
	at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:89):89
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall2(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:766):766
	at content.contentserver_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:257):257
	at content.contentserver_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:307):307
	at content.contentserver_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at content.contentserver_cfc$cf.udfCall2(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:646):646
	at content.contentserver_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
	at index_cfm$cf.call(/var/www/clients/client14/web73/web/index.cfm:46):46
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:861):861
	at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:206):206
	at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2212):2212
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2179):2179
	at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:331):331
	at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722):722
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224):224
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169):169
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472):472
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168):168
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407):407
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579):579
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307):307
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615
	at java.lang.Thread.run(Thread.java:745):745

Column: 0
ID: ??
Line: 1644
Raw Trace: content.contentrenderer_cfc$cf.udfCall6(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1644)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 1779
Raw Trace: content.contentrenderer_cfc$cf.udfCall7(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1779)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 1105
Raw Trace: content.contentrenderer_cfc$cf.udfCall5(/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1105)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 159
Raw Trace: _default.includes.themes.cp.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc:159)
Template: /var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 79
Raw Trace: _default.includes.themes.cp.contentrenderer_cfc$cf.udfCall(/var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc:79)
Template: /var/www/clients/client14/web73/web/default/includes/themes/cp/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 111
Raw Trace: murascope_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/MuraScope.cfc:111)
Template: /var/www/clients/client14/web73/web/requirements/mura/MuraScope.cfc
Type: cfml

Column: 0
ID: ??
Line: 51
Raw Trace: _default.includes.themes.cp.templates.inc.header_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/inc/header.cfm:51)
Template: /var/www/clients/client14/web73/web/default/includes/themes/cp/templates/inc/header.cfm
Type: cfml

Column: 0
ID: ??
Line: 4
Raw Trace: _default.includes.themes.cp.templates.three_column_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/three_column.cfm:4)
Template: /var/www/clients/client14/web73/web/default/includes/themes/cp/templates/three_column.cfm
Type: cfml

Column: 0
ID: ??
Line: 1
Raw Trace: _default.includes.themes.cp.templates.default_cfm$cf.call(/var/www/clients/client14/web73/web/default/includes/themes/cp/templates/default.cfm:1)
Template: /var/www/clients/client14/web73/web/default/includes/themes/cp/templates/default.cfm
Type: cfml

Column: 0
ID: ??
Line: 92
Raw Trace: translator.standardhtmltranslator_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/Translator/standardHTMLTranslator.cfc:92)
Template: /var/www/clients/client14/web73/web/requirements/mura/Translator/standardHTMLTranslator.cfc
Type: cfml

Column: 0
ID: ??
Line: 133
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:133)
Template: /var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 87
Raw Trace: handler.standardeventshandler_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc:87)
Template: /var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 89
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:89)
Template: /var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 409
Raw Trace: handler.standardeventshandler_cfc$cf.udfCall3(/var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc:409)
Template: /var/www/clients/client14/web73/web/requirements/mura/Handler/standardEventsHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 89
Raw Trace: plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc:89)
Template: /var/www/clients/client14/web73/web/requirements/mura/plugin/pluginStandardEventWrapper.cfc
Type: cfml

Column: 0
ID: ??
Line: 766
Raw Trace: content.contentserver_cfc$cf.udfCall2(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:766)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 257
Raw Trace: content.contentserver_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:257)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 307
Raw Trace: content.contentserver_cfc$cf.udfCall1(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:307)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 646
Raw Trace: content.contentserver_cfc$cf.udfCall2(/var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc:646)
Template: /var/www/clients/client14/web73/web/requirements/mura/content/contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 46
Raw Trace: index_cfm$cf.call(/var/www/clients/client14/web73/web/index.cfm:46)
Template: /var/www/clients/client14/web73/web/index.cfm
Type: cfml

Followed @stevewithington instructions [here](https://github.com/blueriver/MuraCMS/issues/1588#issuecomment-90186703)

**Comment by stevewithington** [comment]
This is the first time I've seen this issue reported after following my instructions for updating. What happens when you reload Mura?

**Comment by al3x-edge** [comment]
Same. Reloaded (No Go) -> Cleared Railo Server & Web Caches (No Go) -> Reloaded (No go)   -- Only found issues related to non-clearing cache and double checked I did that. Had to restore from backup for day time. Tried twice and don't have more of a maintenance window. I'll try again tonight.  OTOH, it did upgrade to 6.2.xxxx (latest version) instead of just 6.1

**Comment by stevewithington** [comment]
Please add this to your `/config/settings.ini.cfm` file: `hasurls=false` and try again.

**Comment by al3x-edge** [comment]
@stevewithington Will do. I'll report back tonight. Thanks for the update.

**Comment by stevewithington** [comment]
You really shouldn't even have to add that to your settings.ini.cfm file though. I would also check to make sure the configBean.cfc has this line:
https://github.com/blueriver/MuraCMS/blob/5f5e725ebd6d28f86782583186a0b82fff90377e/requirements/mura/configBean.cfc#L121

If it does, then I would think it has to do with your Template/Component Cache.

**Comment by al3x-edge** [comment]
@stevewithington I added `hasurls=false` and `hashurls=false` to the settings.ini.cfm and no go.  I checked for the `hashURLs` line in the configBean and it's there.   Still no go after cache clears and reloading application.  Mura admin runs, but I'm the site is still displaying the above error.  Going to try to output a site bundle (hopefully works) and then possibly just start from scratch.  Just hinging on the bundle actually working. >.<

**Comment by al3x-edge** [comment]
Still failing out at the same lines -- double checked local file:

```cfc
	<cfif this.hashURLS and len(arguments.queryString) and right(arguments.filename,1) neq "/">
		<cfset arguments.queryString="/" & arguments.queryString>
	</cfif>
```

**Comment by stevewithington** [comment]
@al3x-edge well, without having access to your code/install, it's nearly impossible for me to tell what may be causing it. It's not something I can reproduce and haven't run into anyone else experiencing this issue yet.

It's obviously choking on `this.hashURLs` in that line ... and it makes no sense because if you look through the file, it's set to a boolean if it's not a boolean value already. The only other think you could try doing is wrapping that with `YesNoFormat(this.hashURLs)` in the line from `/var/www/clients/client14/web73/web/requirements/mura/content/contentRenderer.cfc:1779` and see if that works or not. If not, then you've got some deeper issue.

**Comment by al3x-edge** [comment]
Yeah.  Event if I fix the hashURLS issue (It was coming back as a string, not sure why it didn't fail earlier in the method. set it as false before the use), I get a new issue on contentServer.cfc:812 -- Failing on `	<cfif not arguments.siteidinurls>`  which is also coming back as a string >.<

**Comment by al3x-edge** [comment]
Yup.  Definitely anything to do with application.configBean turns into a string.  Ever had anything like that with Railo & Mura?  I would assume string because it's a getter. Getters which don't find a value return an empty string.  Clue as to what might return cause application.configBean not to return?

**Comment by stevewithington** [comment]
No, I've not run into this. What happens when you dump application.configBean? What about application.configBean.getAllValues()?

**Comment by al3x-edge** [comment]
Dumping application.configBean gave me correct output for the configBean methods.  I didn't try `application.configBean.getAllValues()` though. Will have to wait until tomorrow again.  Thanks for the time spent debugging with me.  This mura instance is just a thorn and our others have upgraded successfully using your instructions.

**Comment by stevewithington** [comment]
I suspect an environment issue is the underlying cause. I would check your CF Admin settings to see if there's anything different across your installs that are working.
