### ISSUE TITLE
No matching function [GETINIPROPERTY] found

### ISSUE THREAD

**Issue by tbugler** [blueriver/MuraCMS#1867]
Tried to upgrade MURA Core. First error was can't cast boolean to string. Add the hasurls=false to settings.ini.cfm and configbean.cfc. Now I'm getting No matching function [GETINIPROPERTY] found.

=============================================================================

Catch
Entries: 13
additional	
Struct
cause	
Struct
additional	
Struct
Detail	
string	
ErrNumber	
number	0
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	No matching function [GETINIPROPERTY] found
StackTrace	
string	No matching function [GETINIPROPERTY] found at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source):-1 at config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71):71 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103):103 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49):49 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener._onRequest(Unknown Source):-1 at lucee.runtime.listener.MixedAppListener.onRequest(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(Unknown Source):-1 at lucee.loader.servlet.CFMLServlet.service(Unknown Source):-1 at javax.servlet.http.HttpServlet.service(HttpServlet.java:728):728 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51):51 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243):243 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222):222 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123):123 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171):171 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100):100 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603):603 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310):310 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at java.lang.Thread.run(Thread.java:744):744
TagContext	
Array
1	
Struct
codePrintHTML	
string	69: &lt;!--- do a settings setup check ---&gt;<br> 70: &lt;cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )&gt;<br> <b>71: &lt;cfif getINIProperty(entry=&quot;mode&quot;,section=&quot;settings&quot;) eq &quot;production&quot;&gt;</b><br> 72: &lt;cfif directoryExists( variables.basedir &amp; &quot;/config/setup&quot; )&gt;<br> 73: &lt;cfset application.setupComplete = false /&gt;<br>
codePrintPlain	
string	69:  70: <cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )> 71: <cfif getINIProperty(entry="mode",section="settings") eq "production"> 72: <cfif directoryExists( variables.basedir & "/config/setup" )> 73: <cfset application.setupComplete = false />
column	
number	0
id	
string	??
line	
number	71
Raw_Trace	
string	config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71)
template	
string	C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm
type	
string	cfml
2	
Struct
codePrintHTML	
string	101: &lt;!--- Since the request may of had to wait double thak that code sitll needs to run ---&gt;<br> 102: &lt;cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))&gt;<br> <b>103: &lt;cfinclude template=&quot;onApplicationStart_include.cfm&quot;&gt;</b><br> 104: &lt;cfif isdefined(&quot;setupApplication&quot;)&gt;<br> 105: &lt;cfset setupApplication()&gt;<br>
codePrintPlain	
string	101:  102: <cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))> 103: <cfinclude template="onApplicationStart_include.cfm"> 104: <cfif isdefined("setupApplication")> 105: <cfset setupApplication()>
column	
number	0
id	
string	??
line	
number	103
Raw_Trace	
string	config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm
type	
string	cfml
3	
Struct
codePrintHTML	
string	47: &lt;cffunction name=&quot;onRequestStart&quot; returnType=&quot;boolean&quot; output=&quot;false&quot;&gt;<br> 48: &lt;cfset var local=structNew()&gt;<br> <b>49: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/onRequestStart_include.cfm&quot;&gt;</b><br> 50: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/scriptProtect_include.cfm&quot;&gt;<br> 51: &lt;cfreturn true&gt;<br>
codePrintPlain	
string	47: <cffunction name="onRequestStart" returnType="boolean" output="false"> 48: <cfset var local=structNew()> 49: <cfinclude template="/muraWRM/config/appcfc/onRequestStart_include.cfm"> 50: <cfinclude template="/muraWRM/config/appcfc/scriptProtect_include.cfm"> 51: <cfreturn true>
column	
number	0
id	
string	??
line	
number	49
Raw_Trace	
string	config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm
type	
string	cfml
type	
string	expression
Detail	
string	
ErrNumber	
number	0
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	No matching function [GETINIPROPERTY] found
name	
string	onRequestStart
rootCause	
Struct
additional	
Struct
Detail	
string	
ErrNumber	
number	0
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	No matching function [GETINIPROPERTY] found
StackTrace	
string	No matching function [GETINIPROPERTY] found at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source):-1 at config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71):71 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103):103 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49):49 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener._onRequest(Unknown Source):-1 at lucee.runtime.listener.MixedAppListener.onRequest(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(Unknown Source):-1 at lucee.loader.servlet.CFMLServlet.service(Unknown Source):-1 at javax.servlet.http.HttpServlet.service(HttpServlet.java:728):728 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51):51 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243):243 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222):222 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123):123 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171):171 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100):100 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603):603 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310):310 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at java.lang.Thread.run(Thread.java:744):744
TagContext	
Array
1	
Struct
codePrintHTML	
string	69: &lt;!--- do a settings setup check ---&gt;<br> 70: &lt;cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )&gt;<br> <b>71: &lt;cfif getINIProperty(entry=&quot;mode&quot;,section=&quot;settings&quot;) eq &quot;production&quot;&gt;</b><br> 72: &lt;cfif directoryExists( variables.basedir &amp; &quot;/config/setup&quot; )&gt;<br> 73: &lt;cfset application.setupComplete = false /&gt;<br>
codePrintPlain	
string	69:  70: <cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )> 71: <cfif getINIProperty(entry="mode",section="settings") eq "production"> 72: <cfif directoryExists( variables.basedir & "/config/setup" )> 73: <cfset application.setupComplete = false />
column	
number	0
id	
string	??
line	
number	71
Raw_Trace	
string	config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71)
template	
string	C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm
type	
string	cfml
2	
Struct
codePrintHTML	
string	101: &lt;!--- Since the request may of had to wait double thak that code sitll needs to run ---&gt;<br> 102: &lt;cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))&gt;<br> <b>103: &lt;cfinclude template=&quot;onApplicationStart_include.cfm&quot;&gt;</b><br> 104: &lt;cfif isdefined(&quot;setupApplication&quot;)&gt;<br> 105: &lt;cfset setupApplication()&gt;<br>
codePrintPlain	
string	101:  102: <cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))> 103: <cfinclude template="onApplicationStart_include.cfm"> 104: <cfif isdefined("setupApplication")> 105: <cfset setupApplication()>
column	
number	0
id	
string	??
line	
number	103
Raw_Trace	
string	config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm
type	
string	cfml
3	
Struct
codePrintHTML	
string	47: &lt;cffunction name=&quot;onRequestStart&quot; returnType=&quot;boolean&quot; output=&quot;false&quot;&gt;<br> 48: &lt;cfset var local=structNew()&gt;<br> <b>49: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/onRequestStart_include.cfm&quot;&gt;</b><br> 50: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/scriptProtect_include.cfm&quot;&gt;<br> 51: &lt;cfreturn true&gt;<br>
codePrintPlain	
string	47: <cffunction name="onRequestStart" returnType="boolean" output="false"> 48: <cfset var local=structNew()> 49: <cfinclude template="/muraWRM/config/appcfc/onRequestStart_include.cfm"> 50: <cfinclude template="/muraWRM/config/appcfc/scriptProtect_include.cfm"> 51: <cfreturn true>
column	
number	0
id	
string	??
line	
number	49
Raw_Trace	
string	config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm
type	
string	cfml
type	
string	expression
StackTrace	
string	No matching function [GETINIPROPERTY] found at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source):-1 at config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71):71 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103):103 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49):49 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener.call(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener._onRequest(Unknown Source):-1 at lucee.runtime.listener.MixedAppListener.onRequest(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(Unknown Source):-1 at lucee.loader.servlet.CFMLServlet.service(Unknown Source):-1 at javax.servlet.http.HttpServlet.service(HttpServlet.java:728):728 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51):51 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243):243 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222):222 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123):123 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171):171 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100):100 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603):603 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310):310 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at java.lang.Thread.run(Thread.java:744):744
TagContext	
Array
1	
Struct
codePrintHTML	
string	69: &lt;!--- do a settings setup check ---&gt;<br> 70: &lt;cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )&gt;<br> <b>71: &lt;cfif getINIProperty(entry=&quot;mode&quot;,section=&quot;settings&quot;) eq &quot;production&quot;&gt;</b><br> 72: &lt;cfif directoryExists( variables.basedir &amp; &quot;/config/setup&quot; )&gt;<br> 73: &lt;cfset application.setupComplete = false /&gt;<br>
codePrintPlain	
string	69:  70: <cfif NOT application.setupComplete OR (not application.appInitialized or structKeyExists(url,application.appReloadKey) )> 71: <cfif getINIProperty(entry="mode",section="settings") eq "production"> 72: <cfif directoryExists( variables.basedir & "/config/setup" )> 73: <cfset application.setupComplete = false />
column	
number	0
id	
string	??
line	
number	71
Raw_Trace	
string	config.appcfc.onapplicationstart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm:71)
template	
string	C:\apache\htdocs\config\appcfc\onApplicationStart_include.cfm
type	
string	cfml
2	
Struct
codePrintHTML	
string	101: &lt;!--- Since the request may of had to wait double thak that code sitll needs to run ---&gt;<br> 102: &lt;cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))&gt;<br> <b>103: &lt;cfinclude template=&quot;onApplicationStart_include.cfm&quot;&gt;</b><br> 104: &lt;cfif isdefined(&quot;setupApplication&quot;)&gt;<br> 105: &lt;cfset setupApplication()&gt;<br>
codePrintPlain	
string	101:  102: <cfif (not application.appInitialized or structKeyExists(url,application.appReloadKey))> 103: <cfinclude template="onApplicationStart_include.cfm"> 104: <cfif isdefined("setupApplication")> 105: <cfset setupApplication()>
column	
number	0
id	
string	??
line	
number	103
Raw_Trace	
string	config.appcfc.onrequeststart_include_cfm$cf.call(C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm:103)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_include.cfm
type	
string	cfml
3	
Struct
codePrintHTML	
string	47: &lt;cffunction name=&quot;onRequestStart&quot; returnType=&quot;boolean&quot; output=&quot;false&quot;&gt;<br> 48: &lt;cfset var local=structNew()&gt;<br> <b>49: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/onRequestStart_include.cfm&quot;&gt;</b><br> 50: &lt;cfinclude template=&quot;/muraWRM/config/appcfc/scriptProtect_include.cfm&quot;&gt;<br> 51: &lt;cfreturn true&gt;<br>
codePrintPlain	
string	47: <cffunction name="onRequestStart" returnType="boolean" output="false"> 48: <cfset var local=structNew()> 49: <cfinclude template="/muraWRM/config/appcfc/onRequestStart_include.cfm"> 50: <cfinclude template="/muraWRM/config/appcfc/scriptProtect_include.cfm"> 51: <cfreturn true>
column	
number	0
id	
string	??
line	
number	49
Raw_Trace	
string	config.appcfc.onrequeststart_scriptprotect_method_cfm$cf.udfCall(C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
template	
string	C:\apache\htdocs\config\appcfc\onRequestStart_scriptProtect_method.cfm
type	
string	cfml
type	
string	expression

**Comment by tbugler** [comment]
This site was version 6.2, but the version was still saying 6.1.xxxx. Deleting all of the version.cfm files and reloading Mura had no effect. I grabbed a production version of 6.2.6219 from another server and replaced all of the core files (removed all the version.cfm files), but kept the original settings.ini.cfm file, and did an ?appreload and the site came up. I was then able to update to 6.2.6242
