### ISSUE TITLE
500 error during setup of a local environment 

### ISSUE THREAD

**Issue by jasperboyd** [blueriver/MuraCMS#1910]
Following the instructions word for word created datasource in cf11 with CLOB and the proper permission, my apache config should be squared away. I've gotten this to work with giving it my cf11 credentials but this leads to another problem where all pages throw 404 errors 

    Invalid CFML construct found on line 904 at column 95.
    ColdFusion was looking at the following text:

    =

    The CFML compiler was processing:

    A cfif tag beginning on line 904, column 42.
    A cfif tag beginning on line 904, column 42.
    A cfif tag beginning on line 904, column 42.
    A cfif tag beginning on line 904, column 42.
    A cfif tag beginning on line 904, column 42.
    A cfif tag beginning on line 904, column 42.

     coldfusion.compiler.ParseException: Invalid CFML construct found on line 904 at column 95.
	at coldfusion.compiler.cfml40.generateParseException(cfml40.java:13795)
	at coldfusion.compiler.cfml40.jj_consume_token(cfml40.java:13666)
	at coldfusion.compiler.cfml40.cfif(cfml40.java:308)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4728)
	at coldfusion.compiler.cfml40.cfloop(cfml40.java:1103)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4730)
	at coldfusion.compiler.cfml40.cfif(cfml40.java:311)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4728)
	at coldfusion.compiler.cfml40.cfif(cfml40.java:311)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4728)
	at coldfusion.compiler.cfml40.cfloop(cfml40.java:1103)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4730)
	at coldfusion.compiler.cfml40.cffunction(cfml40.java:4113)
	at coldfusion.compiler.cfml40.cfml(cfml40.java:4744)
	at coldfusion.compiler.cfml40.start(cfml40.java:5054)
	at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:620)
	at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:601)
	at coldfusion.compiler.NeoTranslator.parseAndTransform(NeoTranslator.java:441)
	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:391)
	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:160)
	at coldfusion.runtime.TemplateClassLoader$TemplateCache$1.fetch(TemplateClassLoader.java:461)
	at coldfusion.util.LruCache.get(LruCache.java:180)
	at coldfusion.runtime.TemplateClassLoader$TemplateCache.fetchSerial(TemplateClassLoader.java:387)
	at coldfusion.util.AbstractCache.fetch(AbstractCache.java:58)
	at coldfusion.util.SoftCache.get_statsOff(SoftCache.java:133)
	at coldfusion.util.SoftCache.get(SoftCache.java:81)
	at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:642)
	at coldfusion.runtime.RuntimeServiceImpl.getFile(RuntimeServiceImpl.java:923)
	at coldfusion.runtime.RuntimeServiceImpl.resolveTemplatePath(RuntimeServiceImpl.java:890)
	at coldfusion.runtime.TemplateProxyFactory.getResolvedFile(TemplateProxyFactory.java:1273)
	at coldfusion.runtime.TemplateProxyFactory.getTemplateFileHelper(TemplateProxyFactory.java:1581)
	at coldfusion.runtime.MetadataUtils.getComponentMetadata(MetadataUtils.java:110)
	at coldfusion.runtime.CfJspPage.GetComponentMetadata(CfJspPage.java:2931)
	at cfioc2ecfc824421688$funcCLEANMETADATA.runFunction(/Users/jasperboyd/Sites/MuraCMS/requirements/mura/bean/ioc.cfc:262)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2840)
	at cfioc2ecfc824421688$funcDISCOVERBEANSINFOLDER.runFunction(/Users/jasperboyd/Sites/MuraCMS/requirements/mura/bean/ioc.cfc:400)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2840)
	at cfioc2ecfc824421688$funcDISCOVERBEANS.runFunction(/Users/jasperboyd/Sites/MuraCMS/requirements/mura/bean/ioc.cfc:364)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2840)
	at cfioc2ecfc824421688$funcADDBEAN.runFunction(/Users/jasperboyd/Sites/MuraCMS/requirements/mura/bean/ioc.cfc:57)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfonApplicationStart_include2ecfm1941684663._factor3(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onApplicationStart_include.cfm:179)
	at cfonApplicationStart_include2ecfm1941684663._factor15(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onApplicationStart_include.cfm:161)
	at cfonApplicationStart_include2ecfm1941684663._factor26(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onApplicationStart_include.cfm:102)
	at cfonApplicationStart_include2ecfm1941684663.runPage(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onApplicationStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2986)
	at cfonRequestStart_include2ecfm1097105172._factor0(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onRequestStart_include.cfm:103)
	at cfonRequestStart_include2ecfm1097105172._factor2(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onRequestStart_include.cfm:86)
	at cfonRequestStart_include2ecfm1097105172.runPage(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onRequestStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2986)
	at cfonRequestStart_scriptProtect_method2ecfm1913457779$funcONREQUESTSTART.runFunction(/Users/jasperboyd/Sites/MuraCMS/config/appcfc/onRequestStart_scriptProtect_method.cfm:49)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:455)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:422)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:199)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mattlevine** [comment]
That's a 500 error and not a 404.  Could you try deleting your /requirements/mura directory and replacing it with a fresh download from the git master branch
