### ISSUE TITLE
Unable to associate sitemap or local content index to content objects

### ISSUE THREAD

**Issue by swankc** [blueriver/MuraCMS#1993]
Using core version 6.4.6413 with ColdFusion 10 Update 16 and SQL Server 2008R2. Sitemap window appears with Loading screen and no other options. Content index window opens but when click save it is not added to the content object

**Comment by PeterBowater** [comment]
Also seeing this here,just get the following logged in console:

![screen shot 2015-11-05 at 10 08 29](https://cloud.githubusercontent.com/assets/807991/10965502/3e052fdc-83a5-11e5-8e40-971c29b3a416.png)

**Comment by mattlevine** [comment]
Can you update your core and see if the error persists?

**Comment by PeterBowater** [comment]
Thanks Matt,

Still getting the issue (just updated to most recent), there is a call generating a 500 in the console: 

http://mura6.local:8888/admin/?muraAction=cArch.loadclassconfigurator&compactDisplay=true&siteid=CBI&classid=site_map&contentid=92BB3AE4-1522-43FC-885C815FDB4A8A0E&parentid=00000000000000000000000000000000001&contenthistid=0791F593-E58F-4052-A7CB50AF71B06E75&regionid=2&objectid=02F34468-4A8A-473A-9BFEAC888022D5E3&cacheid=0.16337197227403522&contenttype=Folder&contentsubtype=Default

Resulting in:


500 Error
variable [PARAMS] doesn't exist

Code: 0

Type: 0

variable [PARAMS] doesn't exist
	at railo.runtime.type.scope.UndefinedImpl.get(UndefinedImpl.java:224):224
	at admin.core.views.carch.objectclass.dsp_sitemap_configurator_cfm$cf.call(/Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/objectclass/dsp_sitemap_configurator.cfm:61):61
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:925):925
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:829):829
	at admin.core.views.carch.loadclassconfigurator_cfm$cf.call(/Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/loadclassconfigurator.cfm:79):79
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:925):925
	at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:829):829
	at admin.framework_cfc$cf.udfCall7(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc:1537):1537
	at admin.framework_cfc$cf.udfCall(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:109):109
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:326):326
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:227):227
	at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:764):764
	at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:740):740
	at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1563):1563
	at admin.framework_cfc$cf.udfCall2(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc:548):548
	at admin.framework_cfc$cf.udfCall(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc):-1
	at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:109):109
	at railo.runtime.type.UDFImpl._call(UDFImpl.java:326):326
	at railo.runtime.type.UDFImpl.call(UDFImpl.java:227):227
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:639):639
	at railo.runtime.ComponentImpl._call(ComponentImpl.java:522):522
	at railo.runtime.ComponentImpl.call(ComponentImpl.java:1754):1754
	at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:404):404
	at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:220):220
	at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:34):34
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2228):2228
	at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2195):2195
	at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:353):353
	at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848):848
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686):686
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501):501
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137):137
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575):575
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231):231
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086):1086
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428):428
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193):193
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020):1020
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135):135
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276):276
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103):103
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:566):566
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735):735
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848):848
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686):686
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501):501
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137):137
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557):557
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231):231
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086):1086
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428):428
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193):193
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020):1020
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135):135
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255):255
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154):154
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116):116
	at org.eclipse.jetty.server.Server.handle(Server.java:370):370
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489):489
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949):949
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011):1011
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644):644
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235):235
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82):82
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668):668
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52):52
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608):608
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543):543
	at java.lang.Thread.run(Thread.java:745):745

Column: 0
ID: ??
Line: 61
Raw Trace: admin.core.views.carch.objectclass.dsp_sitemap_configurator_cfm$cf.call(/Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/objectclass/dsp_sitemap_configurator.cfm:61)
Template: /Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/objectclass/dsp_sitemap_configurator.cfm
Type: cfml

Column: 0
ID: ??
Line: 79
Raw Trace: admin.core.views.carch.loadclassconfigurator_cfm$cf.call(/Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/loadclassconfigurator.cfm:79)
Template: /Users/peter/Sites/mura_sites/CBI/admin/core/views/carch/loadclassconfigurator.cfm
Type: cfml

Column: 0
ID: ??
Line: 1537
Raw Trace: admin.framework_cfc$cf.udfCall7(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc:1537)
Template: /Users/peter/Sites/mura_sites/CBI/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 548
Raw Trace: admin.framework_cfc$cf.udfCall2(/Users/peter/Sites/mura_sites/CBI/admin/framework.cfc:548)
Template: /Users/peter/Sites/mura_sites/CBI/admin/framework.cfc
Type: cfml


Thanks for your help,


Peter.

**Comment by mattlevine** [comment]
Please update and retest once more.
