### ISSUE TITLE
ColdFusion 2016 IllegalArgumentException

### ISSUE THREAD

**Issue by nopjmp** [blueriver/MuraCMS#2113]
It appears that crashing in JavaProxy for `NetworkClassLoader`. I added a try catch block to the JavaProxy where it was failing to print out `_getClass().getSimpleName()` to get `NetworkClassLoader`. It also appears that the length of argument appears to be 0.

```
wrong number of arguments

java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3159)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3066)
	at cfJavaProxy2ecfc766688839$funcINIT.runFunction(D:\home\ntc94test.com\wwwroot\requirements\mura\javaloader\JavaProxy.cfc:67)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3089)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3066)
	at cfJavaLoader2ecfc54186930$funcLOADCLASSES.runFunction(D:\home\ntc94test.com\wwwroot\requirements\mura\javaloader\JavaLoader.cfc:261)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3529)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3509)
	at cfJavaLoader2ecfc54186930$funcINIT.runFunction(D:\home\ntc94test.com\wwwroot\requirements\mura\javaloader\JavaLoader.cfc:51)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:464)
	at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:11627)
	at coldfusion.runtime.CFPage._createObject(CFPage.java:11605)
	at cfonApplicationStart_include2ecfm1661018428._factor4(D:\home\ntc94test.com\wwwroot\config\appcfc\onApplicationStart_include.cfm:195)
	at cfonApplicationStart_include2ecfm1661018428._factor15(D:\home\ntc94test.com\wwwroot\config\appcfc\onApplicationStart_include.cfm:161)
	at cfonApplicationStart_include2ecfm1661018428._factor26(D:\home\ntc94test.com\wwwroot\config\appcfc\onApplicationStart_include.cfm:102)
	at cfonApplicationStart_include2ecfm1661018428.runPage(D:\home\ntc94test.com\wwwroot\config\appcfc\onApplicationStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:251)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3683)
	at cfonRequestStart_include2ecfm1362305821._factor0(D:\home\ntc94test.com\wwwroot\config\appcfc\onRequestStart_include.cfm:106)
	at cfonRequestStart_include2ecfm1362305821._factor2(D:\home\ntc94test.com\wwwroot\config\appcfc\onRequestStart_include.cfm:86)
	at cfonRequestStart_include2ecfm1362305821.runPage(D:\home\ntc94test.com\wwwroot\config\appcfc\onRequestStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:251)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3683)
	at cfonRequestStart_scriptProtect_method2ecfm19510264$funcONREQUESTSTART.runFunction(D:\home\ntc94test.com\wwwroot\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:285)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:468)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:286)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:283)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:318)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:285)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:185)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:286)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:283)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:318)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:258)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:185)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:286)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:283)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:318)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:258)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:185)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at com.seefusion.Filter.doFilter(Filter.java:49)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:286)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:283)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:318)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:258)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:185)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:532)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:874)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by nopjmp** [comment]
It appears changing line 67 in the JavaProxy.cfc allows the NetworkClassLoader to load correctly.
From
```
instance = constructor.newInstance(_buildArgumentArray(arguments));
```
To
```
		if (StructCount(arguments) > 0)
		{
			instance = constructor.newInstance(_buildArgumentArray(arguments));
		}
		else
		{
			instance = constructor.newInstance(JavaCast("null", 0));
		}
```

**Comment by mattlevine** [comment]
Can you describe your stack?  What servlet container / java version are you on?

Thanks for digging.
-Matt

**Comment by nopjmp** [comment]
We are running ColdFusion 2016 with its installer. So its the default Tomcat based installation and the default Java version which is Java 1.8.0_72.

**Comment by mattlevine** [comment]
Thanks for suggesting the fix

**Comment by nopjmp** [comment]
@mattlevine it seems my fix only fix part of the problem. I should have mentioned this issue in my commit on my fork, but this should also fix the problem that other have been encountering. Such as https://groups.google.com/d/msg/mura-cms-developers/baQnbhFtb4g/_Zk7g9rGBQAJ . I wasn't able to reproduce where it was working for you while it isn't on our servers. We don't modify any configuration from the default production install.

I can make a pull request if you would or you commit it yourself. It is a small enough fix to not warrant any copyright attribution.

https://github.com/nopjmp/MuraCMS/commit/b6339d30dcdb2cff25474e123610af191f5d64c5

**Comment by mattlevine** [comment]
Have you sent in a contributors agreement?

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

If so a pull request would be great!

**Comment by mattlevine** [comment]
Actually. that's not our code anyway.  So you don't need an agreement,  but it may be nice anyway for anything other issues you may find fixes for.

**Comment by nopjmp** [comment]
I'll make a pull request for the JavaLoader.cfc fix and I'll sign the contributors agreement. Is there a email I need to send it to? I didn't see anything in the contributors agreement for instructions for where to send it.

**Comment by mattlevine** [comment]
Email it to matt.levine@blueriver.com

Thanks a ton!
