### ISSUE TITLE
Bundle deploy and content import issues

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2351]
Hi again chaps, 

Having some problems getting content from my local machine up to a dev server via the export/import routine or using a bundle.

The bundle seems to have a silent exception, the import content routine throws the below error, this is latest version of 7 running on CF9 on Windows:

500 Error
\false (The system cannot find the file specified) 

Type: java.io.FileNotFoundException 

 java.io.FileNotFoundException: \false (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2393)
	at cffileManager2ecfc1645527628$funcEMULATEUPLOAD._factor1(E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc:446)
	at cffileManager2ecfc1645527628$funcEMULATEUPLOAD.runFunction(E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc:432)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfextendManager2ecfc1613951537$funcSAVEEXTENDEDDATA.runFunction(E:\Websites\this-folder\requirements\mura\extend\extendManager.cfc:573)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfcontentManager2ecfc654729547$funcADD.runFunction(E:\Websites\this-folder\requirements\mura\content\contentManager.cfc:1469)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
	at cfcontentManager2ecfc654729547$funcSAVE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentManager.cfc:914)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfcontentBean2ecfc886429746$funcSAVE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentBean.cfc:1135)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfpublisher2ecfc1886656515$funcGETTOWORKPARTIAL.runFunction(E:\Websites\this-folder\requirements\mura\publisher.cfc:509)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
	at cfcontentUtility2ecfc1229979402$funcRESTOREPARTIALBUNDLE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc:167)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
	at cfcontentUtility2ecfc1229979402$funcDEPLOYPARTIALBUNDLE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc:114)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
	at cfcarch2ecfc2124002935$funcIMPORTCONTENT.runFunction(E:\Websites\this-folder\admin\core\controllers\carch.cfc:151)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:389)
	at cfframework2ecfc677965486$funcDOCONTROLLER.runFunction(E:\Websites\this-folder\admin\framework.cfc:1308)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
	at cfframework2ecfc677965486$funcONREQUEST.runFunction(E:\Websites\this-folder\admin\framework.cfc:517)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:88)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:280)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:374)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:94)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126)
	at coldfusion.CfmServlet.service(CfmServlet.java:201)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:86)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.b(FusionReactorFilter.java:376)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.c(FusionReactorFilter.java:254)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.doFilter(FusionReactorFilter.java:164)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at jrun.servlet.FilterChain.service(FilterChain.java:101)
	at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106)
	at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42)
	at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286)
	at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543)
	at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203)
	at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320)
	at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428)
	at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266)
	at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)
 

Column: 0
ID: CF_STRUCTBEAN
Line: 446
Raw Trace: at cffileManager2ecfc1645527628$funcEMULATEUPLOAD._factor1(E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc:446)
Template: E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc
Type: CFML

Column: 0
ID: CF_FILEMANAGER
Line: 432
Raw Trace: at cffileManager2ecfc1645527628$funcEMULATEUPLOAD.runFunction(E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc:432)
Template: E:\Websites\this-folder\requirements\mura\content\file\fileManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 573
Raw Trace: at cfextendManager2ecfc1613951537$funcSAVEEXTENDEDDATA.runFunction(E:\Websites\this-folder\requirements\mura\extend\extendManager.cfc:573)
Template: E:\Websites\this-folder\requirements\mura\extend\extendManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1469
Raw Trace: at cfcontentManager2ecfc654729547$funcADD.runFunction(E:\Websites\this-folder\requirements\mura\content\contentManager.cfc:1469)
Template: E:\Websites\this-folder\requirements\mura\content\contentManager.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 914
Raw Trace: at cfcontentManager2ecfc654729547$funcSAVE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentManager.cfc:914)
Template: E:\Websites\this-folder\requirements\mura\content\contentManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1135
Raw Trace: at cfcontentBean2ecfc886429746$funcSAVE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentBean.cfc:1135)
Template: E:\Websites\this-folder\requirements\mura\content\contentBean.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 509
Raw Trace: at cfpublisher2ecfc1886656515$funcGETTOWORKPARTIAL.runFunction(E:\Websites\this-folder\requirements\mura\publisher.cfc:509)
Template: E:\Websites\this-folder\requirements\mura\publisher.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 167
Raw Trace: at cfcontentUtility2ecfc1229979402$funcRESTOREPARTIALBUNDLE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc:167)
Template: E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 114
Raw Trace: at cfcontentUtility2ecfc1229979402$funcDEPLOYPARTIALBUNDLE.runFunction(E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc:114)
Template: E:\Websites\this-folder\requirements\mura\content\contentUtility.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 151
Raw Trace: at cfcarch2ecfc2124002935$funcIMPORTCONTENT.runFunction(E:\Websites\this-folder\admin\core\controllers\carch.cfc:151)
Template: E:\Websites\this-folder\admin\core\controllers\carch.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 1308
Raw Trace: at cfframework2ecfc677965486$funcDOCONTROLLER.runFunction(E:\Websites\this-folder\admin\framework.cfc:1308)
Template: E:\Websites\this-folder\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 517
Raw Trace: at cfframework2ecfc677965486$funcONREQUEST.runFunction(E:\Websites\this-folder\admin\framework.cfc:517)
Template: E:\Websites\this-folder\admin\framework.cfc
Type: CFML

Thank you!

Peter.

**Comment by PeterBowater** [comment]
Should also be noted, I am experiencing this when export/importing stuff from the home node (kids only) but not on another page, for some reason.

**Comment by mattlevine** [comment]
This looks like the same issue as #2362 .  Please retest this after updating as well.

**Comment by PeterBowater** [comment]
Will do, thanks Matt!
