### ISSUE TITLE
Error when saving via front end

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2362]
Hi again chaps,

Getting some problems when trying to publish pages from the front end, was initially trying to add new display objects, but get the error all the time now, no matter what I do. This is the response to a call to: 

?muraaction=carch.update&action=add&ajaxrequest=true&siteid=raf-aircadets&contenthistid=B63ADD27-5056-A318-A88AC2C69678EE10&contentid=B8129E2E-5056-A318-A8881F7ECC0843C1&parentid=00000000000000000000000000000000001&moduleid=00000000000000000000000000000000000&approved=1&changesetid=&bean=content&loadby=contenthistid&approvalstatus=&csrf_token=0270C0C23D61988473725109A2007BCD&csrf_token_expires=42563.6782870&body=%3Cp%3E%3C%2Fp%3E&objectlist2=&objectlist1=&objectlist3=

Site is Mur7, CF9, Windows Server

Many thanks!

Error runs as follows:

500 Error
\false (The system cannot find the file specified) 

Type: java.io.FileNotFoundException 

 java.io.FileNotFoundException: \false (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2393)
	at cffileManager2ecfc1645527628$funcEMULATEUPLOAD._factor1(E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc:446)
	at cffileManager2ecfc1645527628$funcEMULATEUPLOAD.runFunction(E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc:432)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfextendManager2ecfc1613951537$funcSAVEEXTENDEDDATA.runFunction(E:\Websites\sitename\requirements\mura\extend\extendManager.cfc:573)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfcontentManager2ecfc654729547$funcADD.runFunction(E:\Websites\sitename\requirements\mura\content\contentManager.cfc:1469)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
	at cfcontentManager2ecfc654729547$funcSAVE.runFunction(E:\Websites\sitename\requirements\mura\content\contentManager.cfc:914)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfcontentBean2ecfc886429746$funcSAVE.runFunction(E:\Websites\sitename\requirements\mura\content\contentBean.cfc:1143)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
	at cfcarch2ecfc2124002935$funcUPDATE.runFunction(E:\Websites\sitename\admin\core\controllers\carch.cfc:344)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:389)
	at cfframework2ecfc677965486$funcDOCONTROLLER.runFunction(E:\Websites\sitename\admin\framework.cfc:1308)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
	at cfframework2ecfc677965486$funcONREQUEST.runFunction(E:\Websites\sitename\admin\framework.cfc:517)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:88)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:280)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:374)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:94)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126)
	at coldfusion.CfmServlet.service(CfmServlet.java:201)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:86)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.b(FusionReactorFilter.java:376)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.c(FusionReactorFilter.java:254)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.doFilter(FusionReactorFilter.java:164)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at jrun.servlet.FilterChain.service(FilterChain.java:101)
	at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106)
	at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42)
	at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286)
	at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543)
	at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203)
	at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320)
	at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428)
	at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266)
	at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)
 

Column: 0
ID: CF_STRUCTBEAN
Line: 446
Raw Trace: at cffileManager2ecfc1645527628$funcEMULATEUPLOAD._factor1(E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc:446)
Template: E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc
Type: CFML

Column: 0
ID: CF_FILEMANAGER
Line: 432
Raw Trace: at cffileManager2ecfc1645527628$funcEMULATEUPLOAD.runFunction(E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc:432)
Template: E:\Websites\sitename\requirements\mura\content\file\fileManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 573
Raw Trace: at cfextendManager2ecfc1613951537$funcSAVEEXTENDEDDATA.runFunction(E:\Websites\sitename\requirements\mura\extend\extendManager.cfc:573)
Template: E:\Websites\sitename\requirements\mura\extend\extendManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1469
Raw Trace: at cfcontentManager2ecfc654729547$funcADD.runFunction(E:\Websites\sitename\requirements\mura\content\contentManager.cfc:1469)
Template: E:\Websites\sitename\requirements\mura\content\contentManager.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 914
Raw Trace: at cfcontentManager2ecfc654729547$funcSAVE.runFunction(E:\Websites\sitename\requirements\mura\content\contentManager.cfc:914)
Template: E:\Websites\sitename\requirements\mura\content\contentManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1143
Raw Trace: at cfcontentBean2ecfc886429746$funcSAVE.runFunction(E:\Websites\sitename\requirements\mura\content\contentBean.cfc:1143)
Template: E:\Websites\sitename\requirements\mura\content\contentBean.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 344
Raw Trace: at cfcarch2ecfc2124002935$funcUPDATE.runFunction(E:\Websites\sitename\admin\core\controllers\carch.cfc:344)
Template: E:\Websites\sitename\admin\core\controllers\carch.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 1308
Raw Trace: at cfframework2ecfc677965486$funcDOCONTROLLER.runFunction(E:\Websites\sitename\admin\framework.cfc:1308)
Template: E:\Websites\sitename\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 517
Raw Trace: at cfframework2ecfc677965486$funcONREQUEST.runFunction(E:\Websites\sitename\admin\framework.cfc:517)
Template: E:\Websites\sitename\admin\framework.cfc
Type: CFML

**Comment by PeterBowater** [comment]
As another note, the issue seems most prevalent when trying to add multilevel nav, for which I have custom display object, but even removing that from the theme, and the error still occurs.

Thanks!

Peter.

**Comment by mattlevine** [comment]
Do you have an extended attribute of type File and if so has it been set to a value that is not UUID?  The way they work is that they store the UUID of the FILEID from tfiles.  So if the value being saved is not a UUID it tries  to import it by either looking for a posted file or using the submitted value as a URL which include local file paths.

If you update I put an extra check to ensure that the local file exists before attempting to access it.  So the error should go away.  

Another interesting thing is that it looks like it's saving with a GET and not a POST?  Which is strange.

**Comment by mattlevine** [comment]
Also, can you confirm that you have the layout manger turned on for your site?  To do that you set this.layoutmanager=true; in your theme's contentREnderer.cfc and reload.

**Comment by PeterBowater** [comment]
Thanks Matt, 

Yes, I do have the layout manager enabled, and it is a brand-new 7 install, not an upgrade, so as expected.

No File class extensions, will update and let you know how I get on!

Thanks!


Peter.

**Comment by mattlevine** [comment]
Feel free to reopen this if the fix connected to the issue did not work.
