### ISSUE TITLE
Mura 7 RC doesn't work on ColdFusion 11

### ISSUE THREAD

**Issue by nopjmp** [blueriver/MuraCMS#2370]
We only tested this on ColdFusion 11, but the way paths are being passed around works in Lucee, but ColdFusion requires the mapping to be expanded on some functions.

I added the "expandedPath" variable and used that insteads of arguments.filepath. I'm not sure if the savecontent include needs the expanded path, but this fixed a problem on our server.

EDIT: This is with Sandbox Security enabled

```
component extends="mura.cfobject" {

    function execute(filepath){
        var result='';
        var expandedPath = expandPath(arguments.filepath);

        if(fileExists(expandedPath)){
            var tempfile=createUUID() & '.cfm';
            var tempDir=expandPath('/mura/temp');

            if(!directoryExists(tempDir)){
                directoryCreate(tempDir);
            }

            var temp=fileRead(expandedPath);

            if(findNoCase('cfoutput', temp) || findNoCase('writeoutput', temp)){

                fileWrite(tempDir & "/" & tempfile,temp);

                savecontent variable="result"{
                    include "/mura/temp/#tempfile#";
                }

                fileDelete(tempDir & "/" & tempfile);
            } else {
                result=temp;
            }
        } else {
            savecontent variable="result"{
                include "#filepath#";
            }
        }

        return result;
    }

}
```

**Comment by mattlevine** [comment]
Can you revert and post the stacktrace?  The idea is that if filepath argument is return true with fileExists() then use fileRead().  If it doesn't the assumption is that it's a relative or mapped then use "include".  So it almost seems like fileExists() returns true if for both?

**Comment by mattlevine** [comment]
I kinda merge the two approaches.  Please update and retest.

**Comment by nopjmp** [comment]
That works as well. The stacktrace is below. I forgot to mention that it is Sandbox Security that is causing the problem. This only happens in that type of environment. Adding "\-" and/or "/-" to the rules causes everything to be allowed for every path.

I'm not sure if Adobe will even fix this or add an option, but that should at least workaround these types of situations.
```
access denied ("java.io.FilePermission" "\muraWRM\admin\core\views\carch\objectclass\calendar\config.xml.cfm" "read")

java.security.AccessControlException: access denied ("java.io.FilePermission" "\muraWRM\admin\core\views\carch\objectclass\calendar\config.xml.cfm" "read")
 at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
 at java.security.AccessController.checkPermission(AccessController.java:884)
 at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
 at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
 at java.io.File.isFile(File.java:877)
 at coldfusion.runtime.CFPage.FileExists(CFPage.java:3531)
 at cfexecutor2ecfc1667773465$funcEXECUTE.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\executor.cfc:6)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
 at cfsettingsBean2ecfc1165241706$funcREGISTERDISPLAYOBJECTDIR.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\settings\settingsBean.cfc:1492)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2810)
 at cfsettingsBean2ecfc1165241706$funcDISCOVERDISPLAYOBJECTS.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\settings\settingsBean.cfc:1456)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
 at cfsettingsManager2ecfc183310775$funcSETSITES.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\settings\settingsManager.cfc:421)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
 at cfsettingsManager2ecfc183310775$funcINIT.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\settings\settingsManager.cfc:61)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
 at Statement218.evaluate(<generated>:1)
 at coldfusion.compiler.ExprClassLoader.evaluate(ExprClassLoader.java:149)
 at coldfusion.runtime.CFPage.Evaluate(CFPage.java:2320)
 at cfioc2ecfc1636862487$funcRESOLVEBEANCREATE.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\bean\ioc.cfc:740)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
 at cfioc2ecfc1636862487$funcRESOLVEBEANCREATE.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\bean\ioc.cfc:717)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
 at cfioc2ecfc1636862487$funcRESOLVEBEAN.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\bean\ioc.cfc:620)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
 at cfioc2ecfc1636862487$funcGETBEAN.runFunction(D:\home\durangotelegraph.com\subdomains\staging\requirements\mura\bean\ioc.cfc:132)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
 at cfonApplicationStart_include2ecfm217404205._factor18(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onApplicationStart_include.cfm:357)
 at cfonApplicationStart_include2ecfm217404205._factor26(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onApplicationStart_include.cfm:102)
 at cfonApplicationStart_include2ecfm217404205.runPage(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onApplicationStart_include.cfm:1)
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
 at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
 at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
 at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
 at cfonRequestStart_include2ecfm1193001589._factor0(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onRequestStart_include.cfm:106)
 at cfonRequestStart_include2ecfm1193001589._factor2(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onRequestStart_include.cfm:86)
 at cfonRequestStart_include2ecfm1193001589.runPage(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onRequestStart_include.cfm:1)
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
 at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
 at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
 at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
 at cfonRequestStart_scriptProtect_method2ecfm449823241$funcONREQUESTSTART.runFunction(D:\home\durangotelegraph.com\subdomains\staging\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
 at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
 at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
 at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:455)
 at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
 at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
 at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
 at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
 at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
 at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
 at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
 at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
 at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
 at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
 at coldfusion.CfmServlet.service(CfmServlet.java:219)
 at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
 at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
 at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
 at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at com.seefusion.Filter.doFilter(Filter.java:49)
 at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)
 at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450)
 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.lang.Thread.run(Thread.java:745)

```

**Comment by mattlevine** [comment]
Can you explain more about how "-" and  "/-" work?  I can find any documentation on it?

https://en.wikipedia.org/wiki/Path_(computing)

Thanks,
-Matt

**Comment by nopjmp** [comment]
In Sandbox Security the "-" is a wildcard character. I'm not sure why they didn't just go with something like glob format. So "/-" will match /etc/passwd and /muraWRM/test.cfc and apparently on Windows C:\ColdFusion11\cfusion\lib\seed.properties. This is a major security flaw if we introduced that into our rules.

**Comment by mattlevine** [comment]
Please re-open if this is still an issue
