### ISSUE TITLE
Updated version 7.0.6728 components won't load

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2403]
Hi,  I just updated to version 6728 and now components will not load.  When looking at the error logs on Lucee I get this error. 
www\admin\core\views\carch\loadsitemanager.cfm, line 79

"ERROR","ajp-nio-8905-exec-2","08/24/2016","14:51:48","","Element at position [1] doesn't exist in array
at lucee.runtime.type.ArrayImpl.invalidPosition(ArrayImpl.java:196):196
at lucee.runtime.type.ArrayImpl.getE(ArrayImpl.java:173):173
at lucee.runtime.type.ArrayImpl.get(ArrayImpl.java:126):126
at lucee.runtime.type.util.ArraySupport.get(ArraySupport.java:314):314
at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:256):256
at lucee.runtime.util.VariableUtilImpl.getCollection(VariableUtilImpl.java:250):250
at lucee.runtime.PageContextImpl.getCollection(PageContextImpl.java:1419):1419

there is a bunch more if you want it.

**Comment by mattlevine** [comment]
Does this issue persist if you reload Mura?

**Comment by mattlevine** [comment]
Can you also, make sure you aren't getting cache js.

**Comment by Tigerlady** [comment]
Matt,  I tried restarting the application several times yesterday but it persisted till I went to bed.  This morning I checked again and it is working.  I did try clearing the cache but didn't help yesterday.  Not sure what happened but today it seems ok again. The error was a bit weird.

**Comment by Tigerlady** [comment]
Matt,  I was working along just fine this morning and ran into the same issue.  Components would not load in the admin.  Everything else seemed fine though.  So I logged out then logged back in.  Components showed up again.  If it happens again will let you know.  I will be working on the site most of the day.
