### ISSUE TITLE
An exception occurred when executing method hasnext

### ISSUE THREAD

**Issue by assuthar** [blueriver/MuraCMS#2425]
Hi,

We have installed fresh mura. Once setup completes and click on finish. We get below error.

500 Error
An exception occurred when executing method hasnext. 

Type: Object 

The cause of this exception was that: java.lang.IllegalAccessException: Class coldfusion.runtime.StructBean can not access a member of class java.util.AbstractList$Itr with modifiers "public". 

 coldfusion.runtime.java.MethodExecutionException: An exception occurred when executing method hasnext.
    at coldfusion.runtime.StructBean.invoke(StructBean.java:519)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2465)
    at cfJavaLoader2ecfc21938013$funcENSURENETWORKCLASSLOADERONSERVERSCOPE.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc:424)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2659)
    at cfJavaLoader2ecfc21938013$funcINIT.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc:49)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:518)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:660)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:469)
    at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:10379)
    at coldfusion.runtime.CFPage._createObject(CFPage.java:10356)
    at cfonApplicationStart_include2ecfm729739445._factor4(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:195)
    at cfonApplicationStart_include2ecfm729739445._factor15(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:161)
    at cfonApplicationStart_include2ecfm729739445._factor26(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:102)
    at cfonApplicationStart_include2ecfm729739445.runPage(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:1)
    at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244)
    at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444)
    at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2799)
    at cfonApplicationStart_method2ecfm64918568$funcONAPPLICATIONSTART.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_method.cfm:51)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)
    at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
    at coldfusion.runtime.AppEventInvoker.onApplicationStart(AppEventInvoker.java:231)
    at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:309)
    at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)
    at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
    at coldfusion.filter.PathFilter.invoke(PathFilter.java:112)
    at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
    at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
    at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
    at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
    at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
    at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
    at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
    at coldfusion.CfmServlet.service(CfmServlet.java:219)
    at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
    at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:271)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
    at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:306)
    at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:166)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:299)
    at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:57)
    at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
    at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
    at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:271)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
    at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:306)
    at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:246)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:57)
    at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:189)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalAccessException: Class coldfusion.runtime.StructBean can not access a member of class java.util.AbstractList$Itr with modifiers "public"
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:65)
    at java.lang.reflect.Method.invoke(Method.java:588)
    at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
    ... 101 more

Column: 0
ID: CF_STRUCTBEAN
Line: 424
Raw Trace: at cfJavaLoader2ecfc21938013$funcENSURENETWORKCLASSLOADERONSERVERSCOPE.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc:424)
Template: C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 49
Raw Trace: at cfJavaLoader2ecfc21938013$funcINIT.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc:49)
Template: C:CustomerDatawebspaceswebspace_00256063wwwroot
equirementsmurajavaloaderJavaLoader.cfc
Type: CFML

Column: 0
ID: CF_CFPAGE
Line: 195
Raw Trace: at cfonApplicationStart_include2ecfm729739445._factor4(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:195)
Template: C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONAPPLICATIONSTART_INCLUDE
Line: 161
Raw Trace: at cfonApplicationStart_include2ecfm729739445._factor15(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:161)
Template: C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONAPPLICATIONSTART_INCLUDE
Line: 102
Raw Trace: at cfonApplicationStart_include2ecfm729739445._factor26(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:102)
Template: C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONAPPLICATIONSTART_INCLUDE
Line: 1
Raw Trace: at cfonApplicationStart_include2ecfm729739445.runPage(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm:1)
Template: C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_include.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 51
Raw Trace: at cfonApplicationStart_method2ecfm64918568$funcONAPPLICATIONSTART.runFunction(C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_method.cfm:51)
Template: C:CustomerDatawebspaceswebspace_00256063wwwrootconfigappcfconApplicationStart_method.cfm
Type: CFML

**Comment by mattlevine** [comment]
Can you describe your stack (OS, JAVA Version, CF Version) ?

**Comment by assuthar** [comment]
Hello,

Thank you for getting back to me.

OS is windows 2008 R2 Datacenter
JAVA version 1.6.0_29
CF version is CF10

I have also checked in datasource and found createobject java function is enabled.

Please let me know what else I can check/enable to function this.

When I remove dsn details from config/setting.ini.cfm file in mura the setup works but when click on finish it shows the above error again.

**Comment by mattlevine** [comment]
I have a feeling that the issue is because you're on java 1.6.  Oracle stopped supporting it in 11/12.  I'm guessing that you're not on the latest CF10 service pack.  Would it be possible to apply it an retest.

**Comment by assuthar** [comment]
hi,

can you please share which version  of Java is required for mura cms? How to update CF10 with latest service pack?

**Comment by assuthar** [comment]
Hi,

I have tried to install MURA in cf10 with java version 1.8.0_60 but still it gives the same error.

**Comment by mattlevine** [comment]
To get around this set legacyJavaLoader=false in your config/settings.ini.cfm and reload.
