### ISSUE TITLE
Admin broken after update to Mura 7

### ISSUE THREAD

**Issue by slychief** [blueriver/MuraCMS#2440]
I followed the "How to Upgrade Your Mura Core" steps from this page to upgrade from Mura 6.xxx to mura-7.0.6798:
http://www.getmura.com/blog/mura-cms-v7-release-candidate-now-available/
- Unzip the Mura 7 zip then copy and paste everything except the default directory over your existing Mura install.
- Make a Reload/DBUpdate request to the Mura root (eg. http://yousite.com/?appreload&applydbupdates)

After the update the Web-site still works, but the admin backend seems to be broken with the follwoing error message:

```
500 Error
No matching function member [DATETIMEFORMAT] found, available function members are [append,clear,copy,delete,each,filter,find,findKey,findValue,insert,isEmpty,keyArray,keyExists,keyList,keyTranslate,len,sort,update]
Code: 0
Type: expression

No matching function member [DATETIMEFORMAT] found, available function members are [append,clear,copy,delete,each,filter,find,findKey,findValue,insert,isEmpty,keyArray,keyExists,keyList,keyTranslate,len,sort,update]
    at railo.runtime.type.util.MemberUtil.call(MemberUtil.java:77):77
    at railo.runtime.type.util.StructSupport.call(StructSupport.java:242):242
    at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:723):723
    at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1506):1506
    at user.sessionuserfacade_cfc$cf._2(/www/mura/webapps/ROOT/requirements/mura/user/sessionUserFacade.cfc:250):250
    at user.sessionuserfacade_cfc$cf.udfCall(/www/mura/webapps/ROOT/requirements/mura/user/sessionUserFacade.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:102):102
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:370):370
    at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:274):274
    at railo.runtime.type.util.StructSupport.callWithNamedValues(StructSupport.java:249):249
    at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:749):749
    at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1521):1521
    at user.sessionuserfacade_cfc$cf._3(/www/mura/webapps/ROOT/requirements/mura/user/sessionUserFacade.cfc:264):264
    at user.sessionuserfacade_cfc$cf.udfCall(/www/mura/webapps/ROOT/requirements/mura/user/sessionUserFacade.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:102):102
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:370):370
    at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:274):274
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:607):607
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:489):489
    at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1798):1798
    at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:749):749
    at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1521):1521
    at murascope_cfc$cf._4(/www/mura/webapps/ROOT/requirements/mura/MuraScope.cfc:578):578
    at murascope_cfc$cf.udfCall(/www/mura/webapps/ROOT/requirements/mura/MuraScope.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:102):102
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:370):370
    at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:274):274
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:607):607
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:489):489
    at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1798):1798
    at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:749):749
    at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1521):1521
    at admin.core.views.clogin.main_cfm$cf.call(/www/mura/webapps/ROOT/admin/core/views/clogin/main.cfm:203):203
    at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:801):801
    at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:748):748
    at admin.framework_cfc$cf._7(/www/mura/webapps/ROOT/admin/framework.cfc:1538):1538
    at admin.framework_cfc$cf.udfCall(/www/mura/webapps/ROOT/admin/framework.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:102):102
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:370):370
    at railo.runtime.type.UDFImpl.call(UDFImpl.java:283):283
    at railo.runtime.type.util.StructSupport.call(StructSupport.java:240):240
    at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:723):723
    at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1506):1506
    at admin.framework_cfc$cf._2(/www/mura/webapps/ROOT/admin/framework.cfc:548):548
    at admin.framework_cfc$cf.udfCall(/www/mura/webapps/ROOT/admin/framework.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:102):102
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:370):370
    at railo.runtime.type.UDFImpl.call(UDFImpl.java:283):283
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:606):606
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:489):489
    at railo.runtime.ComponentImpl.call(ComponentImpl.java:1779):1779
    at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:350):350
    at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:185):185
    at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18
    at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2248):2248
    at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2215):2215
    at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:312):312
    at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723):723
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290):290
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233):233
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191):191
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127):127
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103):103
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109):109
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293):293
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861):861
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606):606
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489):489
    at java.lang.Thread.run(Thread.java:745):745
```

**Comment by slychief** [comment]
Seems to be a coldfusion compatibility problem.

Which version is required for Mura 7?

**Comment by mattlevine** [comment]
CF 10 and up.  What version are you on?  CF9 is no longer supported by Adobe as well.

**Comment by slychief** [comment]
OK thanks! I am still on a railo setup. Do you know of a guide how to migrate to CF? I guess the only solution will be to create a site bundle, remove the old installtion, install CF 10 and Mura and deploy the bundle.

btw. I managed to fix the problem by removing the function calls.

**Comment by PeterBowater** [comment]
Works fine on Railo 4.5, you could use Commandbox to get you up and running quickly on Lucee -the successor to Railo.

**Comment by mattlevine** [comment]
Mura 7 no longer supports CF9
