### ISSUE TITLE
Cannot Create Local Content Indexes

### ISSUE THREAD

**Issue by tbugler** [blueriver/MuraCMS#2460]
Upgrade to Core 7.0.6282

Throws a database error

Datasource: -----

SQL: SELECT tcontent.ContentHistID, tcontent.ContentID, tcontent.Approved, tcontent.filename, tcontent.Active, tcontent.Type, tcontent.OrderNo, tcontent.ParentID, tcontent.Title, tcontent.menuTitle, tcontent.lastUpdate, tcontent.lastUpdateBy, tcontent.lastUpdateByID, tcontent.Display, tcontent.DisplayStart, tcontent.subtype, tcontent.DisplayStop, tcontent.isnav, tcontent.restricted, count(tcontent2.parentid) AS hasKids,tcontent.isfeature,tcontent.inheritObjects,tcontent.target,tcontent.targetParams, tcontent.islocked,tcontent.releaseDate,tfiles.fileSize,tfiles.fileExt, 2 AS Priority, tcontent.nextn, tfiles.fileid, tcontent.majorVersion, tcontent.minorVersion, tcontentstats.lockID, tcontentstats.lockType, tcontent.expires,tfiles.filename as assocFilename, tcontentfilemetadata.altText as fileAltText, CASE WHEN tcontent.title = 'Events' or tcontent.menuTitle = 'Events' THEN 0 ELSE 1 END AS superSort FROM tcontent LEFT JOIN tcontent tcontent2 ON (tcontent.contentid=tcontent2.parentid) LEFT JOIN tcontentstats on (tcontent.contentID=tcontentstats.contentID and tcontent.siteID=tcontentstats.siteID ) Left Join tfiles ON (tcontent.fileID=tfiles.fileID) Left Join tcontentfilemetadata on (tcontent.fileid=tcontentfilemetadata.fileid and tcontent.contenthistid=tcontentfilemetadata.contenthistid) WHERE tcontent.Active = 1 AND tcontent.siteid = 'cdeaf' AND tcontent.type in ('Page','Folder','Calendar','File','Link','Gallery','Form','Component','Variation') and ( tcontent.Title like '%Events%' or tcontent.menuTitle like '%Events%' or tcontent.summary like '%Events%' or ( tcontent.type not in ('Link','File') and tcontent.body like '%Events%' ) or tcontent.contenthistid in ( select distinct tcontent.contenthistid from tclassextenddata inner join tcontent on (tclassextenddata.baseid=tcontent.contenthistid) where tcontent.active=1 and tcontent.siteid='cdeaf' and tclassextenddata.attributeValue like '%Events%' ) ) and not ( tcontent.Title = 'Events' or tcontent.menuTitle = 'Events' ) and tcontent.moduleid='00000000000000000000000000000000000' GROUP BY tcontent.ContentHistID, tcontent.ContentID, tcontent.Approved, tcontent.filename, tcontent.Active, tcontent.Type, tcontent.OrderNo, tcontent.ParentID, tcontent.Title, tcontent.menuTitle, tcontent.lastUpdate, tcontent.lastUpdateBy, tcontent.lastUpdateByID, tcontent.Display, tcontent.DisplayStart, tcontent.subtype, tcontent.DisplayStop, tcontent.isnav, tcontent.restricted,tcontent.isfeature,tcontent.inheritObjects, tcontent.target,tcontent.targetParams,tcontent.islocked,tcontent.releaseDate,tfiles.fileSize,tfiles.fileExt, tcontent.nextn, tfiles.fileid, tcontent.majorVersion, tcontent.minorVersion, tcontentstats.lockID, tcontentstats.lockType, tcontent.expires,tfiles.filename,tcontentfilemetadata.altText, CASE WHEN tcontent.title = 'Events' or tcontent.menuTitle = 'Events' THEN 0 ELSE 1 END UNION SELECT tcontent.ContentHistID, tcontent.ContentID, tcontent.Approved, tcontent.filename, tcontent.Active, tcontent.Type, tcontent.OrderNo, tcontent.ParentID, tcontent.Title, tcontent.menuTitle, tcontent.lastUpdate, tcontent.lastUpdateBy, tcontent.lastUpdateByID, tcontent.Display, tcontent.DisplayStart, tcontent.subtype, tcontent.DisplayStop, tcontent.isnav, tcontent.restricted, count(tcontent2.parentid) AS hasKids,tcontent.isfeature,tcontent.inheritObjects,tcontent.target,tcontent.targetParams, tcontent.islocked,tcontent.releaseDate,tfiles.fileSize,tfiles.fileExt, 1 AS Priority, tcontent.nextn, tfiles.fileid, tcontent.majorVersion, tcontent.minorVersion, tcontentstats.lockID, tcontentstats.lockType, tcontent.expires,tfiles.filename as assocFilename, tcontentfilemetadata.altText as fileAltText, CASE WHEN tcontent.title = 'Events' or tcontent.menuTitle = 'Events' THEN 0 ELSE 1 END AS superSort FROM tcontent LEFT JOIN tcontent tcontent2 ON (tcontent.contentid=tcontent2.parentid) LEFT JOIN tcontentstats on (tcontent.contentID=tcontentstats.contentID and tcontent.siteID=tcontentstats.siteID ) Left Join tfiles ON (tcontent.fileID=tfiles.fileID) Left Join tcontentfilemetadata on (tcontent.fileid=tcontentfilemetadata.fileid and tcontent.contenthistid=tcontentfilemetadata.contenthistid) WHERE tcontent.Active = 1 and tcontent.moduleid='00000000000000000000000000000000000' AND tcontent.siteid = 'cdeaf' AND tcontent.type in ('Page','Folder','Calendar','File','Link','Gallery','Form','Component','Variation') and ( tcontent.Title = 'Events' or tcontent.menuTitle = 'Events' ) GROUP BY tcontent.ContentHistID, tcontent.ContentID, tcontent.Approved, tcontent.filename, tcontent.Active, tcontent.Type, tcontent.OrderNo, tcontent.ParentID, tcontent.Title, tcontent.menuTitle, tcontent.lastUpdate, tcontent.lastUpdateBy, tcontent.lastUpdateByID, tcontent.Display, tcontent.DisplayStart, tcontent.subtype, tcontent.DisplayStop, tcontent.isnav, tcontent.restricted,tcontent.isfeature,tcontent.inheritObjects, tcontent.target,tcontent.targetParams,tcontent.islocked,tcontent.releaseDate,tfiles.fileSize,tfiles.fileExt,tcontent.nextn, tfiles.fileid, tcontent.majorVersion, tcontent.minorVersion, tcontentstats.lockID, tcontentstats.lockType, tcontent.expires,tfiles.filename, tcontentfilemetadata.altText, CASE WHEN tcontent.title = 'Events' or tcontent.menuTitle = 'Events' THEN 0 ELSE 1 END ORDER BY supersort, priority, tcontent.title 

Code: 0 

Type: database 

Unknown column 'tcontent.title' in 'order clause' 

			
				
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method):-2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62):62
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45):45
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422):422
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411):411
	at com.mysql.jdbc.Util.getInstance(Util.java:386):386
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052):1052
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096):4096
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028):4028
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490):2490
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651):2651
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683):2683
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144):2144
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1375):1375
	at lucee.runtime.db.driver.state.StateUtil.execute(StateUtil.java:145):145
	at lucee.runtime.db.driver.state.StatePreparedStatement.execute(StatePreparedStatement.java:135):135
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:240):240
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:252):252
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:802):802
	at lucee.runtime.tag.Query.doEndTag(Query.java:604):604
	at content.contentgatewayadobe_cfc$cf.udfCall4(/mura/content/contentGatewayAdobe.cfc:1801):1801
	at content.contentgatewayadobe_cfc$cf.udfCall(/mura/content/contentGatewayAdobe.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1606):1606
	at content.contentmanager_cfc$cf.udfCall5(/mura/content/contentManager.cfc:2011):2011
	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596
	at admin.core.views.cfeed.loadsite_cfm$cf.call(/muraWRM/admin/core/views/cfeed/loadsite.cfm:65):65
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:954):954
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:858):858
	at admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1538):1538
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596
	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:548):548
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:414):414
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:223):223
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:37):37
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2268):2268
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2231):2231
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729):729
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217):217
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518):518
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844):844
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673):673
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500):1500
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456):1456
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61
	at java.lang.Thread.run(Thread.java:745):745

**Comment by mattlevine** [comment]
Please update your core once more and retest

https://github.com/blueriver/MuraCMS/commit/d2e832d1bbbc6308c33fa5a232f543907730b256

**Comment by tbugler** [comment]
That resolved the issue.

**Comment by tbugler** [comment]
Thanks Matt!

Sent from Nine<http://www.9folders.com/>
________________________________
