### ISSUE TITLE
After clearing cookies, cookie.mobileformat undefined

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2488]
Hi chaps,

Working on a site, after dumping the cookies on the machine, I get the following error message appear (CF9, Win2K3 -yes I know):

500 Error
Element MOBILEFORMAT is undefined in COOKIE. 

Type: Expression 

 coldfusion.runtime.UndefinedElementException: Element MOBILEFORMAT is undefined in COOKIE.
	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1724)
	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1677)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1812)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1805)
	at cfonRequestStart_include2ecfm2080457388._factor2(E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm:246)
	at cfonRequestStart_include2ecfm2080457388.runPage(E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:231)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:416)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2722)
	at cfonRequestStart_scriptProtect_method2ecfm1931920718$funcONREQUESTSTART.runFunction(E:\Websites\SPLARGE\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:88)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:258)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:367)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:94)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:201)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:86)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.b(FusionReactorFilter.java:376)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.c(FusionReactorFilter.java:254)
	at com.intergral.fusionreactor.filter.FusionReactorFilter.doFilter(FusionReactorFilter.java:164)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
	at jrun.servlet.FilterChain.service(FilterChain.java:101)
	at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106)
	at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42)
	at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286)
	at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543)
	at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203)
	at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320)
	at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428)
	at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266)
	at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)

Column: 0
ID: ??
Line: 246
Raw Trace: at cfonRequestStart_include2ecfm2080457388._factor2(E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm:246)
Template: E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONREQUESTSTART_INCLUDE
Line: 1
Raw Trace: at cfonRequestStart_include2ecfm2080457388.runPage(E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm:1)
Template: E:\Websites\SPLARGE\config\appcfc\onRequestStart_include.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 49
Raw Trace: at cfonRequestStart_scriptProtect_method2ecfm1931920718$funcONREQUESTSTART.runFunction(E:\Websites\SPLARGE\config\appcfc\onRequestStart_scriptProtect_method.cfm:49)
Template: E:\Websites\SPLARGE\config\appcfc\onRequestStart_scriptProtect_method.cfm
Type: CFML

Doesn't appear to be anything theme related, so any ideas? Mura version 7.0.6852 so pretty recent.

TVM!

Peter.

**Comment by mattlevine** [comment]
What version of CF/Lucee are you on? That "should" be set with this code:

https://github.com/blueriver/MuraCMS/blob/develop/config/appcfc/onRequestStart_include.cfm#L228-L244

There was a adjustment to the setCookie method that happened that may play a role if preventing this in the future.  Here's the latest:

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/utility.cfc#L635-L673

However, I'll add one more check to hopefully prevent it from ever happening.

-Matt

**Comment by mattlevine** [comment]
I see now that you're on CF9. I added CF9 patch to work around the issue, but Mura 7 doe not officially support CF9 and CF10 is about to lose Adobe support.  I would update to CF2016, but if that's not an option then I would update to Lucee.

**Comment by PeterBowater** [comment]
Thanks Matt, appreciated.

Our hands are currently tied to CF9, so will have to struggle on. Fingers crossed we can move it to lucee, that is certainly the long term plan.

Will update and let you know tomorrow.

Cheers,

Peter

**Comment by PeterBowater** [comment]
Tested this morning, Matt, all good :)

One further issue, which I suspect you will be unlikely to want to fix is the autoupdater is broken on CF9, obviously I can get around this by doing it manually, which is what I did, just flagging in case you come across it again.

Many thanks again!

Peter.
