### ISSUE TITLE
500 Element Undefined Error While Installing Plugin

### ISSUE THREAD

**Issue by bradmarshall** [blueriver/MuraCMS#2496]
I get a 500 error when installing my own custom plugin. The error is:

`Element PLUGINXML.PLUGIN.SETTINGS is undefined in RC.`

This error was caused by my plugin's `config.xml.cfm` file missing the `<settings>` element. As soon as I included an empty `<settings>` element, the problem went away. My plugin doesn't need any settings and [the v6 docs state that the element is optional](http://docs.getmura.com/v6/back-end/plugins/configxmlcfm/) so I thought I was safe to exclude it.

If it's now required in v7 we could use a friendly error message but if it is in fact optional, it seems like there's a reference or two that could be double-checked in whatever code is loading the XML/installing the plugin?

Thanks!

Mura Core Version:
7.0.6879

Full Stacktrace:
```500 Error
Element PLUGINXML.PLUGIN.SETTINGS is undefined in RC. 

Type: Expression 

 coldfusion.runtime.UndefinedElementException: Element PLUGINXML.PLUGIN.SETTINGS is undefined in RC.
	at coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:109)
	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1664)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1843)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1836)
	at cfeditplugin2ecfm730035274.runPage(/Library/WebServer/Documents/MuraCMS7/admin/core/views/csettings/editplugin.cfm:115)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
	at cfframework2ecfc97721494$funcINTERNALVIEW.runFunction(/Library/WebServer/Documents/MuraCMS7/admin/framework.cfc:1538)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
	at cfframework2ecfc97721494$funcONREQUEST.runFunction(/Library/WebServer/Documents/MuraCMS7/admin/framework.cfc:548)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:462)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
 

Column: 0
ID: CF_DOTRESOLVER
Line: 115
Raw Trace: at cfeditplugin2ecfm730035274.runPage(/Library/WebServer/Documents/MuraCMS7/admin/core/views/csettings/editplugin.cfm:115)
Template: /Library/WebServer/Documents/MuraCMS7/admin/core/views/csettings/editplugin.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 1538
Raw Trace: at cfframework2ecfc97721494$funcINTERNALVIEW.runFunction(/Library/WebServer/Documents/MuraCMS7/admin/framework.cfc:1538)
Template: /Library/WebServer/Documents/MuraCMS7/admin/framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 548
Raw Trace: at cfframework2ecfc97721494$funcONREQUEST.runFunction(/Library/WebServer/Documents/MuraCMS7/admin/framework.cfc:548)
Template: /Library/WebServer/Documents/MuraCMS7/admin/framework.cfc
Type: CFML```

**Comment by bradmarshall** [comment]
Tested and confirmed working! Thanks!
