### ISSUE TITLE
Error after latest update : key [ADMINDIR] doesn't exist 

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2506]
```sh
500 Error
key [ADMINDIR] doesn't exist 

Code: 0 

Type: expression 

			
				key [ADMINDIR] doesn't exist
	at lucee.runtime.type.util.StructSupport.invalidKey(StructSupport.java:66):66
	at lucee.runtime.type.StructImpl.get(StructImpl.java:120):120
	at lucee.runtime.type.util.StructSupport.get(StructSupport.java:237):237
	at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:255):255
	at lucee.runtime.PageContextImpl.get(PageContextImpl.java:1435):1435
	at configbean_cfc$cf.udfCallb(/var/www/requirements/mura/configBean.cfc:1140):1140
	at configbean_cfc$cf.udfCall(/var/www/requirements/mura/configBean.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:641):641
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1760):1760
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:742):742
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1589):1589
	at content.contentrendererutility_cfc$cf.udfCall3(/var/www/requirements/mura/content/contentRendererUtility.cfc:765):765
	at content.contentrendererutility_cfc$cf.udfCall(/var/www/requirements/mura/content/contentRendererUtility.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1777):1777
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:773):773
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1599):1599
	at content.contentrenderer_cfc$cf.udfCall7(/var/www/requirements/mura/content/contentRenderer.cfc:2022):2022
	at content.contentrenderer_cfc$cf.udfCall(/var/www/requirements/mura/content/contentRenderer.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1773):1773
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221):221
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194):194
	at murascope_cfc$cf.udfCall1(/var/www/requirements/mura/MuraScope.cfc:111):111
	at murascope_cfc$cf.udfCall(/var/www/requirements/mura/MuraScope.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:641):641
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:565):565
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:526):526
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1777):1777
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:773):773
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1599):1599
	at admin.core.views.carch.edit_cfm$cf.call(/var/www/admin/core/views/carch/edit.cfm:465):465
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:950):950
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:854):854
	at admin.framework_cfc$cf.udfCall7(/var/www/admin/framework.cfc:1538):1538
	at admin.framework_cfc$cf.udfCall(/var/www/admin/framework.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:742):742
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1589):1589
	at admin.framework_cfc$cf.udfCall2(/var/www/admin/framework.cfc:548):548
	at admin.framework_cfc$cf.udfCall(/var/www/admin/framework.cfc):-1
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:641):641
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1760):1760
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:405):405
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:221):221
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:35):35
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2257):2257
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2224):2224
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731):731
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303):303
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241):241
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220):220
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122):122
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505):505
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170):170
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103):103
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957):957
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116):116
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423):423
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079):1079
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620):620
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316):316
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61
	at java.lang.Thread.run(Thread.java:745):745

			

Column: 0
ID: ??
Line: 1140
Raw Trace: configbean_cfc$cf.udfCallb(/var/www/requirements/mura/configBean.cfc:1140)
Template: /var/www/requirements/mura/configBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 765
Raw Trace: content.contentrendererutility_cfc$cf.udfCall3(/var/www/requirements/mura/content/contentRendererUtility.cfc:765)
Template: /var/www/requirements/mura/content/contentRendererUtility.cfc
Type: cfml

Column: 0
ID: ??
Line: 2022
Raw Trace: content.contentrenderer_cfc$cf.udfCall7(/var/www/requirements/mura/content/contentRenderer.cfc:2022)
Template: /var/www/requirements/mura/content/contentRenderer.cfc
Type: cfml

Column: 0
ID: ??
Line: 111
Raw Trace: murascope_cfc$cf.udfCall1(/var/www/requirements/mura/MuraScope.cfc:111)
Template: /var/www/requirements/mura/MuraScope.cfc
Type: cfml

Column: 0
ID: ??
Line: 465
Raw Trace: admin.core.views.carch.edit_cfm$cf.call(/var/www/admin/core/views/carch/edit.cfm:465)
Template: /var/www/admin/core/views/carch/edit.cfm
Type: cfml

Column: 0
ID: ??
Line: 1538
Raw Trace: admin.framework_cfc$cf.udfCall7(/var/www/admin/framework.cfc:1538)
Template: /var/www/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 548
Raw Trace: admin.framework_cfc$cf.udfCall2(/var/www/admin/framework.cfc:548)
Template: /var/www/admin/framework.cfc
Type: cfml

```

**Comment by mattlevine** [comment]
Strange, that should be set here:

https://github.com/blueriver/MuraCMS/blob/master/requirements/mura/configBean.cfc#L190

Can you try deleting your /config/version.cfm and re-autoupdating your core?

-Matt

**Comment by rwatts3** [comment]
Thank you I'll give that a shot

**Comment by rwatts3** [comment]
Thank you Matt, 

This solution fixed the problem. 
I am looking forward to Muracon tomorrow. 

Thanks again, 

Ryan.
