### ISSUE TITLE
Cannot login to admin: Class not found: BCrypt 

### ISSUE THREAD

**Issue by didgiman** [blueriver/MuraCMS#2510]
Hi,

I'm running a Mura 7 site on a CF9 server.

When logging in to the site admin, I get the following error:

Object Instantiation Exception. 
Type: Object 
Class not found: BCrypt 
 coldfusion.runtime.java.JavaObjectClassNotFoundException: Object Instantiation Exception.
	at coldfusion.runtime.java.JavaProxyFactory.getProxy(JavaProxyFactory.java:109)
	at coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:65)
	at coldfusion.runtime.CFPage.createObjectProxy(CFPage.java:4991)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:4955)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:4896)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:4874)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:4831)
	at cfutility2ecfc1128073350$funcGETBCRYPT.runFunction(C:\_...\requirements\mura\utility.cfc:74)

Any idea's how to fix this?

Thanks,
Wim.

**Comment by mattlevine** [comment]
Mura 7 does not support CF9.  In fact Adobe does not support CF9.  I would look into using Lucee is price is an issue with upgrading your stack.

You can try setting config/settings.ini.cfm legacyJavaLoader=true and reload.
