### ISSUE TITLE
Mura Session error - Access after Installation - coldfusion.runtime.AppHelper

### ISSUE THREAD

**Issue by shajfk** [blueriver/MuraCMS#2593]
I have downloaded MURA (Ver 7.0.6980 ) running on CF2016 server.  As soon as we tried to access the application  we are getting the following exception. The Mura application should work with CF2016 server according to its spec. Could you please check the below exception and let us know is there any known issue  or provide any feed back on the exception 

>>>

tried to access method coldfusion.runtime.SessionTracker.setSessionScope(Ljava/lang/String;Ljava/lang/String;Lcoldfusion/runtime/SessionScope;)V from class coldfusion.runtime.AppHelper
Type: java.lang.IllegalAccessError

java.lang.IllegalAccessError: tried to access method coldfusion.runtime.SessionTracker.setSessionScope(Ljava/lang/String;Ljava/lang/String;Lcoldfusion/runtime/SessionScope;)V from class coldfusion.runtime.AppHelper
                at coldfusion.runtime.AppHelper.setupClassicSessionScope(AppHelper.java:1026)
                at coldfusion.runtime.AppHelper.setupSessionScope(AppHelper.java:1143)
                at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:410)
                at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
                at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
                at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
                at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
                at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
                at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
                at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
                at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
                at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
                at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
                at coldfusion.CfmServlet.service(CfmServlet.java:219)
                at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
                at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at com.seefusion.Filter.doFilter(Filter.java:49)
                at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
                at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)
                at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:536)
                at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:898)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:745)

<<<

**Comment by mattlevine** [comment]
Is it possible to gain access to where this problem is happening?
-Matt

**Comment by mattlevine** [comment]
What version of ACF 2016 are you on?  Here's a thread that seems to describing a similar issue what was fixed in subsequent release.

https://forums.adobe.com/thread/2119549

-Matt
