### ISSUE TITLE
Re-order content bug - 7.1

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraCMS#2604]
When I re-order content in 7.1 I get the following error. When I return to the admin the content is re-ordered so seems to be happening on the content list reloading after the re-order operation has taken place.

500 Error

The getContentID method was not found.

Type:Object

Either there are no methods with the specified method name and argument types or the getContentID method is overloaded with argument types that ColdFusion cannot decipher reliably. ColdFusion found 0 methods that match the provided arguments. If this is a Java object and you verified that the method exists, use the javacast function to reduce ambiguity.

coldfusion.runtime.java.MethodSelectionException: The getContentID method was not found.
	at coldfusion.runtime.java.ObjectHandler.findMethodUsingCFMLRules(ObjectHandler.java:383)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:524)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2553)
	at cfMuraScope2ecfc84626148$funcRENDEREVENT.runFunction(D:\home\website.com\bowlneba\core\mura\MuraScope.cfc:378)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cftemplate2ecfm74278657._factor10(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:267)
	at cftemplate2ecfm74278657._factor12(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:48)
	at cftemplate2ecfm74278657._factor13(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:48)
	at cftemplate2ecfm74278657.runPage(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
	at cfdefault2ecfm402946061.runPage(D:\home\website.com\bowlneba\admin\common\layouts\default.cfm:4)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
	at cfframework2ecfc1368562344$funcINTERNALLAYOUT.runFunction(D:\home\website.com\bowlneba\admin\framework.cfc:1903)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
	at cfframework2ecfc1368562344$funcONREQUEST.runFunction(D:\home\website.com\bowlneba\admin\framework.cfc:906)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:462)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
	at com.seefusion.Filter.doFilter(Filter.java:49)
	at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Column: 0
ID: CF_STRUCTBEAN
Line: 378
Raw Trace: at cfMuraScope2ecfc84626148$funcRENDEREVENT.runFunction(D:\home\website.com\bowlneba\core\mura\MuraScope.cfc:378)
Template: D:\home\website.com\bowlneba\core\mura\MuraScope.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 267
Raw Trace: at cftemplate2ecfm74278657._factor10(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:267)
Template: D:\home\website.com\bowlneba\admin\common\layouts\template.cfm
Type: CFML

Column: 0
ID: CF_TEMPLATE
Line: 48
Raw Trace: at cftemplate2ecfm74278657._factor12(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:48)
Template: D:\home\website.com\bowlneba\admin\common\layouts\template.cfm
Type: CFML

Column: 0
ID: CF_TEMPLATE
Line: 48
Raw Trace: at cftemplate2ecfm74278657._factor13(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:48)
Template: D:\home\website.com\bowlneba\admin\common\layouts\template.cfm
Type: CFML

Column: 0
ID: CF_TEMPLATE
Line: 1
Raw Trace: at cftemplate2ecfm74278657.runPage(D:\home\website.com\bowlneba\admin\common\layouts\template.cfm:1)
Template: D:\home\website.com\bowlneba\admin\common\layouts\template.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 4
Raw Trace: at cfdefault2ecfm402946061.runPage(D:\home\website.com\bowlneba\admin\common\layouts\default.cfm:4)
Template: D:\home\website.com\bowlneba\admin\common\layouts\default.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 1903
Raw Trace: at cfframework2ecfc1368562344$funcINTERNALLAYOUT.runFunction(D:\home\website.com\bowlneba\admin\framework.cfc:1903)
Template: D:\home\website.com\bowlneba\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 906
Raw Trace: at cfframework2ecfc1368562344$funcONREQUEST.runFunction(D:\home\website.com\bowlneba\admin\framework.cfc:906)
Template: D:\home\website.com\bowlneba\admin\framework.cfc
Type: CFML

**Comment by mattlevine** [comment]
This should now be fixed

https://github.com/blueriver/MuraCMS/commit/86efd15b559849f6d4fde77cfa53dc09001c8f47

Thanks,
-Matt
