### ISSUE TITLE
INSTANCE.ADMINDIR error after updating to core/site 7.0.7016 

### ISSUE THREAD

**Issue by LeadingEdges** [blueriver/MuraCMS#2613]
I get the following error when trying to edit a page.

500 ERROR

Element INSTANCE.ADMINDIR is undefined in VARIABLES. 

Type: Expression 

 coldfusion.runtime.UndefinedElementException: Element INSTANCE.ADMINDIR is undefined in VARIABLES.
	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1808)
	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1726)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1875)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
	at cfconfigBean2ecfc1556782226$funcGETADMINDIR.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\configBean.cfc:1141)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfcontentRendererUtility2ecfc977063957$funcDSPZOOM.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRendererUtility.cfc:748)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfcontentRenderer2ecfc1862681117$funcDSPZOOM.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRenderer.cfc:2009)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:406)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2992)
	at cfMuraScope2ecfc1279062334$funcONMISSINGMETHOD.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\MuraScope.cfc:111)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:291)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:664)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfedit2ecfm262395567._factor10(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:465)
	at cfedit2ecfm262395567._factor33(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:374)
	at cfedit2ecfm262395567.runPage(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:373)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
	at cfframework2ecfc985898995$funcINTERNALVIEW.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc:1538)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2845)
	at cfframework2ecfc985898995$funcONREQUEST.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc:548)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:462)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:134)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doNext(FusionReactorRequestHandler.java:802)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doHttpServletRequest(FusionReactorRequestHandler.java:339)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doFusionRequest(FusionReactorRequestHandler.java:215)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.handle(FusionReactorRequestHandler.java:839)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorCoreFilter.doFilter(FusionReactorCoreFilter.java:36)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:71)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intergral.fusionreactor.agent.filter.FusionReactorStaticFilter.doFilter(FusionReactorStaticFilter.java:53)
	at com.intergral.fusionreactor.agent.pointcuts.NewFilterChainPointCut$1.invoke(NewFilterChainPointCut.java:41)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Column: 0
ID: ??
Line: 1141
Raw Trace: at cfconfigBean2ecfc1556782226$funcGETADMINDIR.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\configBean.cfc:1141)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\configBean.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 748
Raw Trace: at cfcontentRendererUtility2ecfc977063957$funcDSPZOOM.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRendererUtility.cfc:748)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRendererUtility.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 2009
Raw Trace: at cfcontentRenderer2ecfc1862681117$funcDSPZOOM.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRenderer.cfc:2009)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\content\contentRenderer.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 111
Raw Trace: at cfMuraScope2ecfc1279062334$funcONMISSINGMETHOD.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\MuraScope.cfc:111)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\requirements\mura\MuraScope.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 465
Raw Trace: at cfedit2ecfm262395567._factor10(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:465)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm
Type: CFML

Column: 0
ID: CF_EDIT
Line: 374
Raw Trace: at cfedit2ecfm262395567._factor33(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:374)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm
Type: CFML

Column: 0
ID: CF_EDIT
Line: 373
Raw Trace: at cfedit2ecfm262395567.runPage(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm:373)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\admin\core\views\carch\edit.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 1538
Raw Trace: at cfframework2ecfc985898995$funcINTERNALVIEW.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc:1538)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 548
Raw Trace: at cfframework2ecfc985898995$funcONREQUEST.runFunction(C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc:548)
Template: C:\inetpub\vhosts\neshoba.org\httpdocs\admin\framework.cfc
Type: CFML

**Comment by mattlevine** [comment]
If your admin is functional I would delete your /config/version.cfm and re-update the core once more.  Otherwise, you may want to try manually updating your core:

1. Back everything up, especially your config/settings.ini.cfm

2. Download the latest Mura standard and unzip it to your desktop

3. Copy everything by the "default" directory and paste it over your Mura root

4. If not on windows get your backed up config/settings.ini.cfm and restore it.

5. Make a request to your Mura root in the browser with your appreloadkey and applydbupdates in the url.  By default it would be http://domain.com/?appreload&applydbupdates

**Comment by LeadingEdges** [comment]
Resetting the version worked. Luckily I didn’t have to do steps 1-5 J

Thanks Matt!

Brandon Thomas | Senior Web Developer
LEADING EDGES
2100 Eighth Street  |  Meridian, MS  39301
p: 601.483.9810  |  f: 601.485.6976
www.LeadingEdges.net<http://www.leadingedges.net/>
