### ISSUE TITLE
DB Error: ExtendedAttr DefaultValue too long

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#2621]
While attempting to create an Extended Attribute with a default value for either a Textarea or HTMLEditor field type, a 500 error occurs: data truncation/defaultValue too long [output below].

The defaultValue i'd like isn't terribly long:
<span class="cite-name" itemprop="author creator name">{{Name Here}}</span> :: <span class="cite-title" itemprop="jobTitle">{{Job Title}}</span>

Use case: ^This will be used for a Citation field for a new Page/Quote Type.

Can the defaultValue field be given a max length [for UX], or ideally, the db column be adjusted to accept a longer value, to prevent this type of error? 

___
500 Error
Error Executing Database Query.
SQL: Insert into tclassextendattributes (ExtendSetID,siteID,name,hint,type,isActive,orderno,adminOnly,required,validation,regex,message,label,defaultValue,optionList,optionLabelList) values( (param 1) , (param 2) , (param 3) , (param 4) , (param 5) , 1, 1, 0, (param 6) , (param 7) , (param 8) , (param 9) , (param 10) , (param 11) , (param 12) , (param 13) ) 

Code:22001

Type:Database

Data truncation: Data too long for column 'defaultValue' at row 1

coldfusion.tagext.sql.QueryTag$DatabaseQueryException: Error Executing Database Query.
	at coldfusion.tagext.sql.QueryTag.startQueryExecution(QueryTag.java:866)
	at coldfusion.tagext.sql.QueryTag.doEndTag(QueryTag.java:768)
	at cfextendAttribute2ecfc1903007521$funcSAVE._factor10(/Users/Shared/_www/bp.dev/requirements/mura/extend/extendAttribute.cfc:411)
	at cfextendAttribute2ecfc1903007521$funcSAVE.runFunction(/Users/Shared/_www/bp.dev/requirements/mura/extend/extendAttribute.cfc:391)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3095)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3072)
	at cfcextend2ecfc308805136$funcUPDATEATTRIBUTE.runFunction(/Users/Shared/_www/bp.dev/admin/core/controllers/cextend.cfc:232)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:464)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3017)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2992)
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:477)
	at cfframework2ecfc1426927944$funcDOCONTROLLER.runFunction(/Users/Shared/_www/bp.dev/admin/framework.cfc:1308)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3542)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3522)
	at cfframework2ecfc1426927944$funcONREQUEST.runFunction(/Users/Shared/_www/bp.dev/admin/framework.cfc:517)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:307)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:480)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:363)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:507)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'defaultValue' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at coldfusion.server.j2ee.sql.JRunPreparedStatement.execute(JRunPreparedStatement.java:101)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1547)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1281)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1211)
	at coldfusion.sql.SqlImpl.execute(SqlImpl.java:406)
	at coldfusion.tagext.sql.QueryTag.executeQuery(QueryTag.java:1202)
	at coldfusion.tagext.sql.QueryTag.startQueryExecution(QueryTag.java:815)
	... 90 more

**Comment by cfmitrah** [comment]
Hi @mattlevine 

In DB, contains default column having 100 length varchar. Issue happens while we give greater than 100 length, because there is no restriction length for default value. As of now I restrict the default value field below the max length of DB.

**Pull Request:** https://github.com/blueriver/MuraCMS/pull/2797
