### ISSUE TITLE
500 Error on Launch

### ISSUE THREAD

**Issue by IamProgrammer84** [blueriver/MuraCMS#2648]
I am trying to run MURA version 7 on CF 2016 and getting below error on initial loading.

500 Error
Element SERVICEFACTORY is undefined in APPLICATION.
Type:Expression

coldfusion.runtime.UndefinedElementException: Element SERVICEFACTORY is undefined in APPLICATION.

	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:2213)

	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:2131)

	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2402)

	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2392)

	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2353)

	at cfApplication2ecfc774911024$funcSETUPAPPLICATION._factor0(D:\ServerBox\Sites\GIT\admin\Application.cfc:160)

	at cfApplication2ecfc774911024$funcSETUPAPPLICATION.runFunction(D:\ServerBox\Sites\GIT\admin\Application.cfc:140)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3544)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3524)

	at cfframework2ecfc629987681$funcSETUPAPPLICATIONWRAPPER.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:1082)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3544)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3524)

	at cfframework2ecfc629987681$funcONAPPLICATIONSTART.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:439)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:653)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:442)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:412)

	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)

	at coldfusion.runtime.AppEventInvoker.onApplicationStart(AppEventInvoker.java:237)

	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:345)

	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)

	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)

	at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)

	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)

	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)

	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)

	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)

	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)

	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)

	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)

	at coldfusion.CfmServlet.service(CfmServlet.java:219)

	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)

	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

	at com.seefusion.Filter.doFilter(Filter.java:49)

	at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

	at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)

	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:536)

	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:898)

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:745)

Column: 0
ID: ??
Line: 160
Raw Trace: at cfApplication2ecfc774911024$funcSETUPAPPLICATION._factor0(D:\ServerBox\Sites\GIT\admin\Application.cfc:160)
Template: D:\ServerBox\Sites\GIT\admin\Application.cfc
Type: CFML

Column: 0
ID: CF_APPLICATION
Line: 140
Raw Trace: at cfApplication2ecfc774911024$funcSETUPAPPLICATION.runFunction(D:\ServerBox\Sites\GIT\admin\Application.cfc:140)
Template: D:\ServerBox\Sites\GIT\admin\Application.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 1082
Raw Trace: at cfframework2ecfc629987681$funcSETUPAPPLICATIONWRAPPER.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:1082)
Template: D:\ServerBox\Sites\GIT\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 439
Raw Trace: at cfframework2ecfc629987681$funcONAPPLICATIONSTART.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:439)
Template: D:\ServerBox\Sites\GIT\admin\framework.cfc
Type: CFML

**Comment by mattlevine** [comment]
As a test can you make a request to the Mura root, does it get a similar error?
-Matt

**Comment by IamProgrammer84** [comment]
While going to admin page got this error

500 Error
Element SERVICEFACTORY is undefined in APPLICATION.
Type:Expression
coldfusion.runtime.UndefinedElementException: Element SERVICEFACTORY is undefined in APPLICATION.

        at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:2213)

        at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:2131)

        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2402)

        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2392)

        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2353)

        at cfApplication2ecfc774911024$funcSETUPAPPLICATION._factor0(D:\ServerBox\Sites\GIT\admin\Application.cfc:160)

        at cfApplication2ecfc774911024$funcSETUPAPPLICATION.runFunction(D:\ServerBox\Sites\GIT\admin\Application.cfc:140)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

        at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

        at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

        at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

        at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

        at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3544)

        at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3524)

        at cfframework2ecfc629987681$funcSETUPAPPLICATIONWRAPPER.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:1082)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

        at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

        at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)

        at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

        at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

        at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

        at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3544)

        at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3524)

        at cfframework2ecfc629987681$funcONAPPLICATIONSTART.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:439)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)

        at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)

        at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

        at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)

        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)

        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:653)

        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:442)

        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:412)

        at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)

        at coldfusion.runtime.AppEventInvoker.onApplicationStart(AppEventInvoker.java:237)

        at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:345)

        at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)

        at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)

        at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)

        at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)

        at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)

        at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)

        at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)

        at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)

        at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)

        at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)

        at coldfusion.CfmServlet.service(CfmServlet.java:219)

        at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

        at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)

        at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

        at com.seefusion.Filter.doFilter(Filter.java:49)

        at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)

        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

        at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)

        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)

        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:536)

        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:898)

        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)

        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

        at java.lang.Thread.run(Thread.java:745)


________________________________
Column: 0
ID: ??
Line: 160
Raw Trace: at cfApplication2ecfc774911024$funcSETUPAPPLICATION._factor0(D:\ServerBox\Sites\GIT\admin\Application.cfc:160)
Template: D:\ServerBox\Sites\GIT\admin\Application.cfc
Type: CFML
________________________________
Column: 0
ID: CF_APPLICATION
Line: 140
Raw Trace: at cfApplication2ecfc774911024$funcSETUPAPPLICATION.runFunction(D:\ServerBox\Sites\GIT\admin\Application.cfc:140)
Template: D:\ServerBox\Sites\GIT\admin\Application.cfc
Type: CFML
________________________________
Column: 0
ID: CF_UDFMETHOD
Line: 1082
Raw Trace: at cfframework2ecfc629987681$funcSETUPAPPLICATIONWRAPPER.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:1082)
Template: D:\ServerBox\Sites\GIT\admin\framework.cfc
Type: CFML
________________________________
Column: 0
ID: CF_UDFMETHOD
Line: 439
Raw Trace: at cfframework2ecfc629987681$funcONAPPLICATIONSTART.runFunction(D:\ServerBox\Sites\GIT\admin\framework.cfc:439)
Template: D:\ServerBox\Sites\GIT\admin\framework.cfc
Type: CFML


While going to root dir got this error,

500 Error
tried to access method coldfusion.runtime.SessionTracker.setSessionScope(Ljava/lang/String;Ljava/lang/String;Lcoldfusion/runtime/SessionScope;)V from class coldfusion.runtime.AppHelper
Type:java.lang.IllegalAccessError

Please let me know if you need more information.



Thanks
Ramesh Balajepalli

**Comment by mattlevine** [comment]
What happens when you don't go to the admin.  When it's a request to the Mura root?  The application.serviceFactory should be defined.  Perhaps try a manually reload by putting this in the url ?appreload&applydbupdates

**Comment by mattlevine** [comment]
And use the ?appreload&applydbupdates with a request to the Mura root and not the admin.

**Comment by IamProgrammer84** [comment]
Sorry for the late response, the URL param’s didn’t help, still getting same error messages.

Thanks
Ramesh Balajepalli

**Comment by mattlevine** [comment]
Unfortunately, we can't reproduce your issue.  If you want to provide me with access I could take a look?

-Matt

**Comment by IamProgrammer84** [comment]
Sure, gotomeeting works ? if so, please let me know your convenient time and I will send you the link.

Thanks
Ramesh Balajepalli

**Comment by mattlevine** [comment]
I don't really consider a screen share as access.  If you can give ssh or ftp access to where the issue is happening I can take a look when I have time.
