### ISSUE TITLE
500 error when exporting a class extension after deleting a plugin

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2686]
To reproduce:
- install MuraPlugin
- delete it
- try to export a class extension

I get the following 500 error. Reloading the application does not help, but restarting ColdFusion fixes it.

500 Error
Could not find the included template ../../plugin/settings.cfm.
Type:MissingInclude
Note: If you wish to use an absolute template path (for example, template="/mypath/index.cfm") with include, you must create a mapping for the path using the ColdFusion Administrator. Or, you can use per-application settings to specify mappings specific to this application by specifying a mappings struct to THIS.mappings in Application.cfc. <br> Using relative paths (for example, template="index.cfm" or template="../index.cfm") does not require the creation of any special mappings. It is therefore recommended that you use relative paths with include whenever possible.

coldfusion.tagext.lang.IncludeTag$NoSuchIncludeTemplateException: Could not find the included template ../../plugin/settings.cfm.

	at coldfusion.tagext.lang.IncludeTag.setTemplate(IncludeTag.java:432)

	at cfmuraplugin2ecfc331944685.runPage(Z:\vhost\mura7\plugins\MuraPlugin\model\handlers\muraplugin.cfc:12)

	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:538)

	at coldfusion.runtime.TemplateProxyFactory.resolveNameForDuplicate(TemplateProxyFactory.java:165)

	at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:47)

	at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:72)

	at coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:68)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2535)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Array.Duplicate(Array.java:105)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:90)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2541)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2567)

	at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2542)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Array.Duplicate(Array.java:105)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:90)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.Struct.duplicate(Struct.java:153)

	at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)

	at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)

	at coldfusion.runtime.CFPage.Duplicate(CFPage.java:6316)

	at cfextendSet2ecfc889444905$funcGETASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendSet.cfc:464)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)

	at cfextendSubType2ecfc1168640433$funcGETASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendSubType.cfc:933)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)

	at cfextendManager2ecfc1702993660$funcGETSUBTYPESASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendManager.cfc:1681)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)

	at cfcextend2ecfc2129206718$funcEXPORT.runFunction(Z:\vhost\mura7\admin\core\controllers\cextend.cfc:112)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)

	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:406)

	at cfframework2ecfc1681600636$funcDOCONTROLLER.runFunction(Z:\vhost\mura7\admin\framework.cfc:1308)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)

	at cfframework2ecfc1681600636$funcONREQUEST.runFunction(Z:\vhost\mura7\admin\framework.cfc:517)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)

	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)

	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:470)

	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)

	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)

	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)

	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)

	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)

	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)

	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)

	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)

	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)

	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)

	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)

	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)

	at coldfusion.CfmServlet.service(CfmServlet.java:219)

	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)

	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)

	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:466)

	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)

	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Unknown Source)

Column: 0
ID: CFINCLUDE
Line: 12
Raw Trace: at cfmuraplugin2ecfc331944685.runPage(Z:\vhost\mura7\plugins\MuraPlugin\model\handlers\muraplugin.cfc:12)
Template: Z:\vhost\mura7\plugins\MuraPlugin\model\handlers\muraplugin.cfc
Type: CFML

Column: 0
ID: CF_CFPAGE
Line: 464
Raw Trace: at cfextendSet2ecfc889444905$funcGETASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendSet.cfc:464)
Template: Z:\vhost\mura7\requirements\mura\extend\extendSet.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 933
Raw Trace: at cfextendSubType2ecfc1168640433$funcGETASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendSubType.cfc:933)
Template: Z:\vhost\mura7\requirements\mura\extend\extendSubType.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1681
Raw Trace: at cfextendManager2ecfc1702993660$funcGETSUBTYPESASXML.runFunction(Z:\vhost\mura7\requirements\mura\extend\extendManager.cfc:1681)
Template: Z:\vhost\mura7\requirements\mura\extend\extendManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 112
Raw Trace: at cfcextend2ecfc2129206718$funcEXPORT.runFunction(Z:\vhost\mura7\admin\core\controllers\cextend.cfc:112)
Template: Z:\vhost\mura7\admin\core\controllers\cextend.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 1308
Raw Trace: at cfframework2ecfc1681600636$funcDOCONTROLLER.runFunction(Z:\vhost\mura7\admin\framework.cfc:1308)
Template: Z:\vhost\mura7\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 517
Raw Trace: at cfframework2ecfc1681600636$funcONREQUEST.runFunction(Z:\vhost\mura7\admin\framework.cfc:517)
Template: Z:\vhost\mura7\admin\framework.cfc
Type: CFML

**Comment by David-Polehonski** [comment]
It Looks like the files in the model directory (which are registered on load) are cached in memory. However seeing as the plugin has been deleted, the included template referenced by the muraplugin.cfc no longer exists. 

That said I can see no link between line 464 in the extendSet.cfc and anything that would trigger this error. Have you been able to reproduce muliple times?

**Comment by damien-git** [comment]
Yes, I can reproduce it every time.

**Comment by stevewithington** [comment]
@damien-git what version of ACF are you using?

**Comment by stevewithington** [comment]
@damien-git, I'm trying to replicate your issue, and based on the information I have at the moment, I'm unable to do so. 

Just out of curiosity...
1. Did your version of MuraPlugin include any custom class extensions?
2. Do any of your class extension have a call to MuraPlugin to populate any options for the extension?

**Comment by damien-git** [comment]
1. No, but I only tried the old version of the plugin, before your recent change
2. No

**Comment by stevewithington** [comment]
@damien-git, please re-test using the updated version of the plugin, and let me know if you run into the same issue. Thanks.

**Comment by damien-git** [comment]
I just tested it (I edited my previous post but you might not get that if you look at emails). No difference.

**Comment by stevewithington** [comment]
@damien-git what version of Adobe ColdFusion are you using, and what version of Mura?

**Comment by damien-git** [comment]
From the Mura "About" menu:
Core Version 7.0.7044
App Server ColdFusion (11,0,13,303668)

**Comment by stevewithington** [comment]
Documenting test findings:

* Class extension must contain an attribute set with attributes
* MuraPlugin must have been assigned to the site

| Mura Version | CFEngine | Bug |
| --- | --- | --- |
| 7.0 | ACF2016 | Yes |
| 7.0 | ACF11 | Yes |
| 7.0 | Lucee5 | No |
| 7.1 | ACF2016 | Yes |
| 7.1 | ACF11 | Yes |
| 7.1 | Lucee5 | No |

For some reason, the cached `module` paths don't appear to be clearing on appreload (primary issue)
