### ISSUE TITLE
key [remotePubDate] doesn't exist

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraCMS#2693]
This is happening when I edit an existing content item to add an associated image. I do not have a class extension named remotePubDate or any ORM property with that name.

After updating to 7.1.107 I did appreload&applydbupdates. I did it a second time after this error for good measure, didn't help.

**Core** 7.1.107
**Lucee** 5.1.0.34
**MySQL** 5.7.10
**Java** 1.8.0_112
**Windows Server** 2012 R2 (6.3)

key [remotePubDate] doesn't exist

Code:0
Type:expression

lucee.runtime.exp.ExpressionException: key [remotePubDate] doesn't exist

	at lucee.runtime.type.util.StructSupport.invalidKey(StructSupport.java:67)

	at lucee.runtime.type.StructImpl.get(StructImpl.java:134)

	at lucee.runtime.type.util.StructSupport.get(StructSupport.java:242)

	at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:260)

	at lucee.runtime.PageContextImpl.get(PageContextImpl.java:1452)

	at bean.beanorm_cfc$cf.udfCall3(/mura/bean/beanORM.cfc:458)

	at bean.beanorm_cfc$cf.udfCall(/mura/bean/beanORM.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:583)

	at lucee.runtime.SuperComponent.call(SuperComponent.java:82)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at content.file.filebean_cfc$cf.udfCall1(/mura/content/file/fileBean.cfc:115)

	at content.file.filebean_cfc$cf.udfCall(/mura/content/file/fileBean.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)

	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)

	at content.file.filedao_cfc$cf.udfCall1(/mura/content/file/fileDAO.cfc:185)

	at content.file.filedao_cfc$cf.udfCall(/mura/content/file/fileDAO.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)

	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)

	at content.file.filemanager_cfc$cf.udfCall1(/mura/content/file/fileManager.cfc:103)

	at content.file.filemanager_cfc$cf.udfCall(/mura/content/file/fileManager.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)

	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)

	at content.file.filebean_cfc$cf.udfCall1(/mura/content/file/fileBean.cfc:98)

	at content.file.filebean_cfc$cf.udfCall(/mura/content/file/fileBean.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at content.contentmanager_cfc$cf.udfCall4(/mura/content/contentManager.cfc:1403)

	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at content.contentmanager_cfc$cf.udfCall4(/mura/content/contentManager.cfc:915)

	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at content.contentbean_cfc$cf.udfCall7(/mura/content/contentBean.cfc:1014)

	at content.contentbean_cfc$cf.udfCall(/mura/content/contentBean.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at admin.core.controllers.carch_cfc$cf.udfCall2(/muraWRM/admin/core/controllers/carch.cfc:364)

	at admin.core.controllers.carch_cfc$cf.udfCall(/muraWRM/admin/core/controllers/carch.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1911)

	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)

	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)

	at admin.framework_cfc$cf.udfCall6(/admin/framework.cfc:1308)

	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)

	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:517)

	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)

	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)

	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:422)

	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:224)

	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)

	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2293)

	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2284)

	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2252)

	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:891)

	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)

	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)

	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:476)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:745)

Column: 0
ID: ??
Line: 458
Raw Trace: bean.beanorm_cfc$cf.udfCall3(/mura/bean/beanORM.cfc:458)
Template: C:\home\website.com\website\core\mura\bean\beanORM.cfc
Type: cfml

Column: 0
ID: ??
Line: 115
Raw Trace: content.file.filebean_cfc$cf.udfCall1(/mura/content/file/fileBean.cfc:115)
Template: C:\home\website.com\website\core\mura\content\file\fileBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 185
Raw Trace: content.file.filedao_cfc$cf.udfCall1(/mura/content/file/fileDAO.cfc:185)
Template: C:\home\website.com\website\core\mura\content\file\fileDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 103
Raw Trace: content.file.filemanager_cfc$cf.udfCall1(/mura/content/file/fileManager.cfc:103)
Template: C:\home\website.com\website\core\mura\content\file\fileManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 98
Raw Trace: content.file.filebean_cfc$cf.udfCall1(/mura/content/file/fileBean.cfc:98)
Template: C:\home\website.com\website\core\mura\content\file\fileBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 1403
Raw Trace: content.contentmanager_cfc$cf.udfCall4(/mura/content/contentManager.cfc:1403)
Template: C:\home\website.com\website\core\mura\content\contentManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 915
Raw Trace: content.contentmanager_cfc$cf.udfCall4(/mura/content/contentManager.cfc:915)
Template: C:\home\website.com\website\core\mura\content\contentManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1014
Raw Trace: content.contentbean_cfc$cf.udfCall7(/mura/content/contentBean.cfc:1014)
Template: C:\home\website.com\website\core\mura\content\contentBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 364
Raw Trace: admin.core.controllers.carch_cfc$cf.udfCall2(/muraWRM/admin/core/controllers/carch.cfc:364)
Template: C:\home\website.com\website\admin\core\controllers\carch.cfc
Type: cfml

Column: 0
ID: ??
Line: 1308
Raw Trace: admin.framework_cfc$cf.udfCall6(/admin/framework.cfc:1308)
Template: C:\home\website.com\website\admin\framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 517
Raw Trace: admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:517)
Template: C:\home\website.com\website\admin\framework.cfc
Type: cfml

**Comment by grantshepert** [comment]
Try running with ?appreload&applydbupdates in the url. Is the remotePubDate column actually in the tfiles table? If not, make sure the user account the database is running under has permission to alter the tables.

**Comment by mattlevine** [comment]
Hmm,I can't remember exactly what the issue was but tfiles doesn't get updated with the db utility with MySQL.  It simply looks for the 'caption' field and if it's not there it runs a single statement.  This could cause a problem if the caption field is there and not the remotePubDate.  

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/dbUpdates/6.1.cfm#L18-L58

Try creating a temp.cfm in your Mura root with this code and run it in your browser:

```<cfscript>
application.mura.getBean('dbUtility')
    .setTable('tfiles')
    .addColumn(column="caption",dataType="text")
		.addColumn(column="credits",dataType="varchar",length="255")
		.addColumn(column="alttext",dataType="varchar",length="255")
		.addColumn(column="remoteID",dataType="varchar",length="255")
		.addColumn(column="remoteURL",dataType="varchar",length="255")
		.addColumn(column="remotePubDate",dataType="datetime")
		.addColumn(column="remoteSource",dataType="varchar",length="255")
		.addColumn(column="remoteSourceURL",dataType="varchar",length="255")
		.addColumn(column="exif",dataType="text")
		.addIndex('siteid')
		.addIndex('contentid')
		.addIndex('remoteid')
		.addIndex('moduleID');
</cfscript>```

**Comment by bowler865** [comment]
@grantshepert 

I tried ?appreload&applydbupdates a few times before posting the bug report :(

@mattlevine 

Thanks, I ran that and verified that remotePubDate is in tfiles.

Unfortunately the issue is still happening though.

![screen shot 2017-11-16 at 3 55 45 pm](https://user-images.githubusercontent.com/6114711/32915495-10f7fe30-cae7-11e7-9d37-6059eb6d36f1.png)

**Comment by bowler865** [comment]
By the way, I've experienced this while doing the following (in case it helps at all):

1. adding an associated image to an existing page
2. adding an associated image to new page
3. creating a new file content item and attaching a PDF

I was able to add images to existing pages after initially installing 7.1

**Comment by mattlevine** [comment]
I think I fixed the issue, but it's just kinda weird that it all of a sudden showed up?  Please update and retest.

**Comment by bowler865** [comment]
@mattlevine , thanks, that fixed the issue.
