### ISSUE TITLE
Mura 6.2: "Element RC.CONTENTBEAN is undefined in ARGUMENTS" internal error when saving a page

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2717]
One of our users of Mura 6.2 is consistently having this error when saving a page (draft or publish) (she is currently the only non-super user editing the site).

 To sum it up:
```
coldfusion.runtime.EventHandlerException: Event handler exception. [...]
Element RC.CONTENTBEAN is undefined in ARGUMENTS. at [...]
C:\Inetpub\vhosts\siteadmin.natsci.msu.edu\httpdocs\admin\core\controllers\carch.cfc:369 [...]
or:
C:\Inetpub\vhosts\siteadmin.natsci.msu.edu\httpdocs\admin\core\controllers\carch.cfc:386 [...]
(depending on the choice to continue editing)
```

It looks like this error can occur every time `allowAction ` is false because the function does not check that value for everything. I double checked the user permissions: she is in a group that has permission to edit the site and editor permission for the Home page. Other pages on the site inherit from Home. I looked at the database and did not see anything wrong with the entries for the user, group, permission and home page content.

Here is the full stack:
```
Dec 7, 2017 12:21:43 PM Error [ajp-bio-8012-exec-4351] - coldfusion.runtime.EventHandlerException: 
Event handler exception. at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:308) at 
coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:426) at 
coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) at 
coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at 
coldfusion.filter.PathFilter.invoke(PathFilter.java:112) at 
coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) at 
coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at 
coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at 
coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58) at 
coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at 
coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at 
coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at 
coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151) at 
coldfusion.CfmServlet.service(CfmServlet.java:219) at 
coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at 
coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at 
coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at 
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450) at 
org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197) at 
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) at 
org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at 
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at 
java.lang.Thread.run(Unknown Source) Caused by: coldfusion.runtime.UndefinedElementException: Element RC.CONTENTBEAN is undefined in ARGUMENTS. at 
coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:109) at 
coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1639) at 
coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1621) at 
cfcarch2ecfc1002375704$funcUPDATE.runFunction(C:\Inetpub\vhosts\siteadmin.natsci.msu.edu\httpdocs\admin\core\controllers\carch.cfc:369) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at 
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at 
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at 
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at 
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:518) at 
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:660) at 
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:469) at 
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2369) at 
coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:402) at 
cfframework2ecfc574717633$funcDOCONTROLLER.runFunction(C:\Inetpub\vhosts\siteadmin.natsci.msu.edu\httpdocs\admin\framework.cfc:1308) at 
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at 
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at 
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at 
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at 
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at 
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at 
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2655) at 
cfframework2ecfc574717633$funcONREQUEST.runFunction(C:\Inetpub\vhosts\siteadmin.natsci.msu.edu\httpdocs\admin\framework.cfc:517) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at 
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at 
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at 
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at 
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at 
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655) at 
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444) at 
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414) at 
coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108) at 
coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:300) ... 35 more 
```

**Comment by damien-git** [comment]
I found that this error was caused by a bad path value in the database. I do not know what caused that bad path. I am guessing these values also explain another issue we have seen with this site (the first menu was sometimes displayed as if it was the top menu).

For instance:

91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,91421636-155D-E635-18995E6A88E6C922,915222CC-155D-E635-185EF4F861AD4ACD
