### ISSUE TITLE
variable [STRINGKEYLIST] doesn't exist

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2801]
I am a bit confused by this one. The backend of Mura 7.1.1.181 works fine, and the front end was working fine all day too.

Then a site became unresponsive and I restarted Tomcat/Lucee from the command line. After that, I get this error in the frontend.

I copied across a fresh core/mura/ directory and restarted tomcat again as well as reloaded the mura admin. still the same error - any ideas?
DB Server is MySQL 5.7.21 on Ubuntu.

Thanks

---

`500 Error
variable [STRINGKEYLIST] doesn't exist
Code:0
Type:expression
lucee.runtime.exp.ExpressionException: variable [STRINGKEYLIST] doesn't exist
	at lucee.runtime.type.scope.UndefinedImpl.get(UndefinedImpl.java:234)
	at jsonserializer_cfc$cf.udfCall1(/mura/jsonSerializer.cfc:89)
	at jsonserializer_cfc$cf.udfCall(/mura/jsonSerializer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at client.api.json.v1.apiutility_cfc$cf.udfCall1(/mura/client/api/json/v1/apiUtility.cfc:41)
	at client.api.json.v1.apiutility_cfc$cf.udfCall(/mura/client/api/json/v1/apiUtility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2005)
	at lucee.runtime.functions.other._CreateComponent.call(_CreateComponent.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:55)
	at lucee.runtime.reflection.Reflector.callStaticMethod(Reflector.java:928)
	at lucee.runtime.functions.BIFProxy.invoke(BIFProxy.java:41)
	at lucee.runtime.interpreter.ref.func.BIFCall.getValue(BIFCall.java:145)
	at lucee.runtime.interpreter.CFMLExpressionInterpreter.interpret(CFMLExpressionInterpreter.java:220)
	at lucee.runtime.functions.dynamicEvaluation.Evaluate._call(Evaluate.java:109)
	at lucee.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:102)
	at lucee.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:43)
	at settings.settingsbean_cfc$cf.udfCall7(/mura/settings/settingsBean.cfc:1191)
	at settings.settingsbean_cfc$cf.udfCall(/mura/settings/settingsBean.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at core.modules.v1.htmlhead.global_cfm$cf.call(/muraWRM/core/modules/v1/htmlhead/global.cfm:87)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:933)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:805)
	at content.contentrenderer_cfc$cf.udfCallc(/mura/content/contentRenderer.cfc:2791)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at translator.standardhtmltranslator_cfc$cf.udfCall(/mura/Translator/standardHTMLTranslator.cfc:114)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2005)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:140)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at handler.standardeventshandler_cfc$cf.udfCall1(/mura/Handler/standardEventsHandler.cfc:90)
	at handler.standardeventshandler_cfc$cf.udfCall(/mura/Handler/standardEventsHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2001)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at utility_cfc$cf.udfCall7(/mura/utility.cfc:1371)
	at utility_cfc$cf.udfCall(/mura/utility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2005)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:90)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at handler.standardeventshandler_cfc$cf.udfCall3(/mura/Handler/standardEventsHandler.cfc:425)
	at handler.standardeventshandler_cfc$cf.udfCall(/mura/Handler/standardEventsHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2001)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at utility_cfc$cf.udfCall7(/mura/utility.cfc:1371)
	at utility_cfc$cf.udfCall(/mura/utility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2005)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:90)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:839)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:771)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:260)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:771)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:346)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:689)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2005)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:710)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:687)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:567)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1988)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at index_cfm$cf.call(/index.cfm:46)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:933)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:225)
	at lucee.runtime.listener.ModernAppListener.onRequest(ModernAppListener.java:105)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2464)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2454)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2427)
	at lucee.runtime.engine.Request.exe(Request.java:44)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1091)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1039)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Column: 0
ID: ??
Line: 89
Raw Trace: jsonserializer_cfc$cf.udfCall1(/mura/jsonSerializer.cfc:89)`

**Comment by mattlevine** [comment]
Does your Lucee instance not have standard scope cascading?

**Comment by mattlevine** [comment]
Try copying down the update that I just put up.

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/jsonSerializer.cfc

**Comment by JonasEriksson** [comment]
Ahhhh!  Thank you so much, you were totally right - I had the standard on admin/server, but on admin/web I had for some reason changed cascading to "small". I owe you a beer or two for that fast reply - much appreciated!

**Comment by JonasEriksson** [comment]
And just to confirm, switching back to "small" and using your new file, that works as well! (Still switching back to "Standard (CFML default)", I should not change what I don't fully understand, lol.

Closing this with the minor useful feedback that line 3 in your file has a typo: "hint = "This provides a way to serialize **_complext_** ColdFusion data values as case-sensitive JavaScript Object Notation (JSON) strings."
