### ISSUE TITLE
Element FORM.PAGES is undefined in BODYSTRUCT

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2893]
A form we created last year with form builder is no longer working. When we send it, Javascript sends a `processAsyncObject` POST request. Mura returns an HTML error page with a full stack trace (which is a security issue in itself). Looking at the parameters sent with the request, I see a "def" parameter with JSON content. This JSON content has a "form" property, which does not have a "pages" property.
Based on the "blame" page for dataCollectionBean.cfc, this bug could come from https://github.com/blueriver/MuraCMS/pull/2818 .

```
coldfusion.runtime.UndefinedElementException: Element FORM.PAGES is undefined in BODYSTRUCT.
	at coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:109)
	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1664)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1843)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1836)
	at cfdataCollectionBean2ecfc1461506371$funcSENDNOTIFICATION.runFunction(E:\web-files\mura7\core\mura\content\dataCollection\dataCollectionBean.cfc:411)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfdataCollectionBean2ecfc1461506371$funcSUBMIT.runFunction(E:\web-files\mura7\core\mura\content\dataCollection\dataCollectionBean.cfc:375)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfindex2ecfm753578248.runPage(E:\web-files\mura7\core\modules\v1\form\index.cfm:87)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)
	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT_INCLUDE.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:1528)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT_RENDER.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:1443)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfcontentRendererUtility2ecfc1543563231$funcDSPOBJECT.runFunction(E:\web-files\mura7\core\mura\content\contentRendererUtility.cfc:1284)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:2274)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819)
	at cfcfobject2ecfc52254188$funcINVOKEMETHOD.runFunction(E:\web-files\mura7\core\mura\cfobject.cfc:225)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfMuraScope2ecfc884289064$funcONMISSINGMETHOD.runFunction(E:\web-files\mura7\core\mura\MuraScope.cfc:103)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:291)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:664)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at cfapiUtility2ecfc1747204565$funcPROCESSASYNCOBJECT.runFunction(E:\web-files\mura7\core\mura\client\api\json\v1\apiUtility.cfc:3259)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819)
	at Statement14688.evaluate(&lt;generated&gt;:1)
	at coldfusion.compiler.ExprClassLoader.evaluate(ExprClassLoader.java:149)
	at coldfusion.runtime.CFPage.Evaluate(CFPage.java:2326)
	at cfapiUtility2ecfc1747204565$funcPROCESSREQUEST.runFunction(E:\web-files\mura7\core\mura\client\api\json\v1\apiUtility.cfc:764)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfcontentServer2ecfc1974689196$funcHANDLEAPIREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:559)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfcontentServer2ecfc1974689196$funcHANDLEROOTREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:698)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfindex2ecfm1842569852.runPage(E:\web-files\mura7\index.cfm:43)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:474)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:466)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748) 
```

**Comment by damien-git** [comment]
That form is missing the "pages" property. It was created with Mura 6, so perhaps the property has only been added with Mura 7, and deploying a Mura 6 bundle is not adding it. Re-publishing the form fixes the problem, but we can't do that for all our forms...

**Comment by damien-git** [comment]
To clarify, I see 3 bugs here:
1) Forms imported from Mura 6 should keep working
2) A crash happening during a JSON API call should appear somewhere in the log. In this case, administrators had no way to know that forms were not being sent correctly because no error was being logged.
3) The full stack trace should not be sent to end users in any way (unless a site is in dev mode). This is a security issue.

**Comment by mattlevine** [comment]
What happens if you update the form in the admin and retry?

**Comment by mattlevine** [comment]
I'm pushing out a new build now that has additional check to make sure that the pages attribute exists before going into that block of code.
