### ISSUE TITLE
Error when trying to access "Staging" menu item in 7.1.242 (latest) and previous version of 7.1

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraCMS#2909]
Hello,

I'm getting the following error when trying to access the "Staging" menu item to see the list of Change Sets.

If I remove this chunk of code from cchangesets.cfc then the change set list loads correctly. I don't see any obvious syntax errors though.

```
if ( len(rc.tags) ) {
			cfquery( name="local.rstags" ) { //Note: queryExecute() is the preferred syntax but this syntax is easier to convert generically

				writeOutput("select changesetid from tchangesettagassign where tag in (");
				cfqueryparam( list=true, cfsqltype="cf_sql_varchar", value=arguments.rc.tags );

				writeOutput(")");
			}
			if ( local.rstags.recordcount ) {
				feed.addParam(column='changesetid',criteria=valuelist(local.rstags.changesetid),condition="in");
			} else {
				feed.addParam(column='changesetid',criteria='none');
			}
		}
		if ( len(rc.categoryid) ) {
			cfquery( name="local.rscats" ) { //Note: queryExecute() is the preferred syntax but this syntax is easier to convert generically

				writeOutput("select changesetid from tchangesetcategoryassign where categoryid in (");
				cfqueryparam( list=true, cfsqltype="cf_sql_varchar", value=arguments.rc.categoryid );

				writeOutput(")");
			}
			if ( local.rscats.recordcount ) {
				feed.addParam(column='changesetid',criteria=valuelist(local.rscats.changesetid),condition="in");
			} else {
				feed.addParam(column='changesetid',criteria='none');
			}
		}
```

**Here's the full stack trace:**

500 Error
Invalid construct.
Type:Template
A script statement must end with ";".<p>The CFML compiler was processing:<ul><li>A script statement beginning with cfquery on line 80, column 25.<li>A script statement beginning with { on line 79, column 37.<li>A script statement beginning with if on line 79, column 17.<li>A script statement beginning with public on line 63, column 9.</ul>

coldfusion.compiler.ScriptParseExceptions$SemicolonMissingException: Invalid construct.

	at coldfusion.compiler.ScriptParseExceptions.throwSemicolonMissingException(ScriptParseExceptions.java:109)

	at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1599)

	at coldfusion.compiler.cfml40.cfscriptBlock(cfml40.java:2541)

	at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1572)

	at coldfusion.compiler.cfml40.ComplexStatement(cfml40.java:1672)

	at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1530)

	at coldfusion.compiler.cfml40.functionDefinition(cfml40.java:3199)

	at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1577)

	at coldfusion.compiler.cfml40.start(cfml40.java:4848)

	at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:730)

	at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:675)

	at coldfusion.compiler.NeoTranslator.parseAndTransform(NeoTranslator.java:428)

	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:370)

	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:147)

	at coldfusion.runtime.TemplateClassLoader$TemplateCache$1.fetch(TemplateClassLoader.java:442)

	at coldfusion.util.LruCache.get(LruCache.java:180)

	at coldfusion.runtime.TemplateClassLoader$TemplateCache.fetchSerial(TemplateClassLoader.java:362)

	at coldfusion.util.AbstractCache.fetch(AbstractCache.java:58)

	at coldfusion.util.SoftCache.get_statsOff(SoftCache.java:133)

	at coldfusion.util.SoftCache.get(SoftCache.java:81)

	at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:609)

	at coldfusion.runtime.RuntimeServiceImpl.getFile(RuntimeServiceImpl.java:846)

	at coldfusion.runtime.RuntimeServiceImpl.resolveTemplatePath(RuntimeServiceImpl.java:813)

	at coldfusion.runtime.TemplateProxyFactory$ResolveTemplatePathPrivilege.run(TemplateProxyFactory.java:1818)

	at java.security.AccessController.doPrivileged(Native Method)

	at coldfusion.runtime.TemplateProxyFactory.getResolvedFile(TemplateProxyFactory.java:1273)

	at coldfusion.runtime.TemplateProxyFactory.getTemplateFileHelper(TemplateProxyFactory.java:1572)

	at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:51)

	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:5589)

	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:5604)

	at cfframework2ecfc1118537172$funcGETCACHEDCOMPONENT.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1390)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2655)

	at cfframework2ecfc1118537172$funcGETCONTROLLER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1424)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:518)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2620)

	at cfframework2ecfc1118537172$funcCONTROLLER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:173)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2655)

	at cfframework2ecfc1118537172$funcSETUPREQUESTWRAPPER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1224)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2655)

	at cfframework2ecfc1118537172$funcONREQUESTSTART.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:641)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:518)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2620)

	at coldfusion.runtime.SuperScope.invoke(SuperScope.java:18)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2369)

	at cfApplication2ecfc570090297$funcONREQUESTSTART.runFunction(D:\home\website.com\wwwroot\admin\Application.cfc:269)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)

	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)

	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:278)

	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:419)

	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)

	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)

	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112)

	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)

	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)

	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)

	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)

	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)

	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)

	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)

	at coldfusion.CfmServlet.service(CfmServlet.java:219)

	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)

	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)

	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)

	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)

	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)

	at java.security.AccessController.doPrivileged(Native Method)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)

	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)

	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)

	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)

	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)

	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)

	at java.security.AccessController.doPrivileged(Native Method)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)

	at com.seefusion.Filter.doFilter(Filter.java:49)

	at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)

	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)

	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)

	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)

	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)

	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)

	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)

	at java.security.AccessController.doPrivileged(Native Method)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:466)

	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)

	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:748)

Column: 54
Line: 80
Template: D:\home\website.com\wwwroot\admin\core\controllers\cchangesets.cfc
Type: SYNTAX

Column: 0
ID: CF_CFPAGE
Line: 1390
Raw Trace: at cfframework2ecfc1118537172$funcGETCACHEDCOMPONENT.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1390)
Template: D:\home\website.com\wwwroot\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 1424
Raw Trace: at cfframework2ecfc1118537172$funcGETCONTROLLER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1424)
Template: D:\home\website.com\wwwroot\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 173
Raw Trace: at cfframework2ecfc1118537172$funcCONTROLLER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:173)
Template: D:\home\website.com\wwwroot\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 1224
Raw Trace: at cfframework2ecfc1118537172$funcSETUPREQUESTWRAPPER.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:1224)
Template: D:\home\website.com\wwwroot\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 641
Raw Trace: at cfframework2ecfc1118537172$funcONREQUESTSTART.runFunction(D:\home\website.com\wwwroot\admin\framework.cfc:641)
Template: D:\home\website.com\wwwroot\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_SUPERSCOPE
Line: 269
Raw Trace: at cfApplication2ecfc570090297$funcONREQUESTSTART.runFunction(D:\home\website.com\wwwroot\admin\Application.cfc:269)
Template: D:\home\website.com\wwwroot\admin\Application.cfc
Type: CFML

**Comment by mattlevine** [comment]
What version of CF are you on?

**Comment by mattlevine** [comment]
I think the problem is that CF10 does not support cfquery script syntax.  I'll look into converting it to older script query syntax, but I would start to plan on upgrading you CF version.  If cost is an issue I would look into using Lucee.

**Comment by bowler865** [comment]
Thanks for responding. I appreciate it. No need to waste time making something compatible with a version of CF that isn't officially supported. The site has been moved to a CF16 server and all is well.

**Comment by jmpuyo** [comment]
I am not sure becuase I tried looking but could not find documentation on it. I think the cfquery function on cfscript for CF10 is not available. I think it was release after CF10.

you can replace the list function with the following code and it should work:

public function list(rc) output=false {
		var feed=variables.changesetManager.getFeed(argumentCollection=arguments.rc);
		feed.setSiteID(arguments.rc.siteid);
		if ( isDate(rc.startdate) ) {
			feed.addParam(column='publishdate',datatype='date',criteria=arguments.rc.startdate,condition=">=");
		}
		if ( isDate(rc.stopdate) ) {
			arguments.rc.stopdate = DateAdd("d", 1, arguments.rc.stopdate);
			feed.addParam(column='publishdate',datatype='date',criteria=arguments.rc.stopdate,condition="<=");
			if ( !isDate(rc.startdate) ) {
				feed.addParam(column='publishdate',datatype='date',criteria=dateAdd('yyyy',100,now()),condition=">=");
			}
		}
		if ( len(rc.keywords) ) {
			feed.addParam(column='name',criteria=arguments.rc.keywords,condition="contains");
		}
		if ( len(rc.tags) ) {
			local.rstagsQry = new Query();
			local.rstagsQry.setSql("select changesetid from tchangesettagassign where tag in (:valueList)");

			local.rstagsRes = local.rstagsQry.execute();
			local.rstags = local.rstagsRes.getResult();

			/*cfquery( name="local.rstags" ) { //Note: queryExecute() is the preferred syntax but this syntax is easier to convert generically

				writeOutput("select changesetid from tchangesettagassign where tag in (");
				cfqueryparam( list=true, cfsqltype="cf_sql_varchar", value=arguments.rc.tags );

				writeOutput(")");
			}*/
			if ( local.rstags.recordcount ) {
				feed.addParam(column='changesetid',criteria=valuelist(local.rstags.changesetid),condition="in");
			} else {
				feed.addParam(column='changesetid',criteria='none');
			}
		}
		if ( len(rc.categoryid) ) {
			local.rscatsQry = new Query();
			local.rscatsQry.setSql("select changesetid from tchangesettagassign where tag in (:valueList)");

			local.rscatsRes = local.rscatsQry.execute();
			local.rscats = local.rscatsRes.getResult();

			/*cfquery( name="local.rscats" ) { //Note: queryExecute() is the preferred syntax but this syntax is easier to convert generically

				writeOutput("select changesetid from tchangesetcategoryassign where categoryid in (");
				cfqueryparam( list=true, cfsqltype="cf_sql_varchar", value=arguments.rc.categoryid );

				writeOutput(")");
			}*/
			if ( local.rscats.recordcount ) {
				feed.addParam(column='changesetid',criteria=valuelist(local.rscats.changesetid),condition="in");
			} else {
				feed.addParam(column='changesetid',criteria='none');
			}
		}
		arguments.rc.changesets=feed.getIterator();
		arguments.rc.changesets.setNextN(20);
		arguments.rc.changesets.setPage(arguments.rc.page);
	}
