### ISSUE TITLE
When using Mura ORM, customdatasources defined in settings.ini.cfm throw an error.

### ISSUE THREAD

**Issue by jsieber-aca** [blueriver/MuraCMS#2910]
We have two custom datasources defined in our settings.ini.cfm file like this:

customdatasource=datasource1
customdatasource2=datasource2

When trying to use Mura ORM, we get the following error when reloading Mura with the applydbupdates URL variable.

500 Error
Error Executing Database Query.
Datasource:datasource1
Code:42S02
Type:Database
Table 'datasource1.tcontentfeeds' doesn't exist

When reloading and applying db updates, the defined datasource should be used, not the defined custom datasources.

**Comment by mattlevine** [comment]
Custom datasources for Mura ORM don't really relate to the settings.ini.cfm?  Can you create it with an example component and post it here?

**Comment by jsieber-aca** [comment]
Sorry, my explanation is probably poor. We are not trying to use a custom datasource for Mura ORM custom entity, just the existence of having custom datasources in our settings.ini.cfm is causing the issue. If I comment out the two custom datasources that we have in our settings.ini.cfm the appReload and applydbupdates complete without causing the error.

It appears that the only issue is running applydbupdates when you have a custom datasources in the settings.ini.cfm. It does not appear to be related to ORM at all. Sorry about that.

**Comment by jsieber-aca** [comment]
My original report was not clear at all. The issue is a change in behavior with version 7.1 when running applydbupdates. Previously, we were able to have custom datasources defined in the settings.ini.cfm, but now Mura will look for the Mura tables in the wrong database if they exist when running applydbupdates.

**Comment by mattlevine** [comment]
What do you use the custom datasource for?  And can you enable robust debug output and post the stacktrace?  I have no idea why a random settings.ini.cfm attribute would suddenly be used as a datasource for Mura itself?

**Comment by jsieber-aca** [comment]
We use the custom datasources to access and display data from a few other databases we have on our site. We then add the to the application scope in the EventHandler in the onApplicationLoad event using the following:  

<cfset application.customDataSource=getProfileString(expandPath("/muraWRM") & "/config/settings.ini.cfm", "production", "customdatasource" ) />
  <cfset application.customDataSource2=getProfileString(expandPath("/muraWRM") & "/config/settings.ini.cfm", "production", "customdatasource2" ) />

For now, we can hardcode the datasource values in the eventHandler.

Here is the stack trace for when I try to applydbupdates with those values in the setting.ini.cfm:

coldfusion.tagext.sql.QueryTag$DatabaseQueryException: Error Executing Database Query.
	at coldfusion.tagext.sql.DBInfoTag.doEndTag(DBInfoTag.java:177)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3697)
	at cfconfigBean2ecfc1679890179$funcDBTABLECOLUMNS.runFunction(C:\www\local.adventurecycling.org\core\mura\configBean.cfc:960)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3542)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3522)
	at cf52e52ecfm1667205524._factor2(C:\www\local.adventurecycling.org\core\mura\dbUpdates\5.5.cfm:1)
	at cf52e52ecfm1667205524.runPage(C:\www\local.adventurecycling.org\core\mura\dbUpdates\5.5.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
	at cfconfigBean2ecfc1679890179$funcAPPLYDBUPDATES.runFunction(C:\www\local.adventurecycling.org\core\mura\configBean.cfc:879)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074)
	at cfonApplicationStart_include2ecfm719032722._factor37(C:\www\local.adventurecycling.org\core\appcfc\onApplicationStart_include.cfm:376)
	at cfonApplicationStart_include2ecfm719032722._factor49(C:\www\local.adventurecycling.org\core\appcfc\onApplicationStart_include.cfm:95)
	at cfonApplicationStart_include2ecfm719032722.runPage(C:\www\local.adventurecycling.org\core\appcfc\onApplicationStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
	at cfonRequestStart_include2ecfm1921862284._factor0(C:\www\local.adventurecycling.org\core\appcfc\onRequestStart_include.cfm:101)
	at cfonRequestStart_include2ecfm1921862284._factor2(C:\www\local.adventurecycling.org\core\appcfc\onRequestStart_include.cfm:82)
	at cfonRequestStart_include2ecfm1921862284.runPage(C:\www\local.adventurecycling.org\core\appcfc\onRequestStart_include.cfm:2)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
	at cfApplication2ecfc1640292158$funcONREQUESTSTART.runFunction(C:\www\local.adventurecycling.org\admin\Application.cfc:177)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:285)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:473)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:513)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aca.tcontentfeeds' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3737)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3727)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3725)
	at coldfusion.sql.DatabaseMetaDataUtil.getColumns(DatabaseMetaDataUtil.java:505)
	at coldfusion.tagext.sql.DBInfoTag.fetchDBMetaData(DBInfoTag.java:221)
	at coldfusion.tagext.sql.DBInfoTag.doEndTag(DBInfoTag.java:166)
	... 96 more
