### ISSUE TITLE
Variable SESSION is undefined

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2936]
Using Mura 7.1.243 with ACF11, I am frequently seeing this error in the exception log. It looks like this is happening during onSessionEnd, but I have not found where. onSessionEnd_include.cfm does define a session variable, but it's not using it directly...

```
14078 | "Error","scheduler-1","10/18/18","12:55:11",,"Variable SESSION is undefined. "
-- | --
14079 | coldfusion.runtime.UndefinedVariableException: Variable SESSION is undefined.
14080 | at coldfusion.runtime.CfJspPage._get(CfJspPage.java:314)
14081 | at coldfusion.runtime.CfJspPage._get(CfJspPage.java:298)
14082 | at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1532)
14083 | at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1494)
14084 | at cfapplication2ecfc1444500990$funcONSESSIONEND.runFunction([web application root]\application.cfc:199)
14085 | at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
14086 | at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
14087 | at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
14088 | at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
14089 | at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
14090 | at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
14091 | at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
14092 | at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
14093 | at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:589)
14094 | at coldfusion.cfc.CFCProxyFilter.invokeAppEvent(CFCProxyFilter.java:102)
14095 | at coldfusion.cfc.CFCProxyFilter.invoke(CFCProxyFilter.java:43)
14096 | at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
14097 | at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
14098 | at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
14099 | at coldfusion.cfc.CFCProxy.doInvoke(CFCProxy.java:328)
14100 | at coldfusion.cfc.CFCProxy.invoke(CFCProxy.java:302)
14101 | at coldfusion.runtime.AppEventInvoker.onSessionEnd(AppEventInvoker.java:456)
14102 | at coldfusion.runtime.SessionTracker.invokeOnSessinEnd(SessionTracker.java:339)
14103 | at coldfusion.runtime.SessionTracker.cleanUp(SessionTracker.java:323)
14104 | at coldfusion.runtime.SessionTracker.access$000(SessionTracker.java:38)
14105 | at coldfusion.runtime.SessionTracker$SessionCleanUpAgent.run(SessionTracker.java:511)
14106 | at coldfusion.scheduling.ThreadPool.run(ThreadPool.java:260)
```

**Comment by mattlevine** [comment]
This should at least improved.  However, I would point out that since session's do not exists within a onSessionEnd request you'll need to make sure to use getSession() from within Mura's object model when referencing it.
