### ISSUE TITLE
Error after updating to 7.1.300 - key [getDefaults] doesn't exist

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2940]
After updating I get this, appreload yields same. I am on Lucee (latest stable), MySQL. I do not use Mura MXP or Adobe CF, which these seem to hang on.

Full stack trace:
`500 Error

key [getDefaults] doesn't exist (existing keys:visitorStatus,keywords,rememberMe,copySiteID,cfid,flatViewArgs,m00000000000000000000000000000000003,mura,paramGroups,dashboardSpan,LOCALE,SITEARRAY,paramCircuit,copyContentID,DATEKEYFORMAT,paramArray,USERFILESPATH,m00000000000000000000000000000000099,blockLoginUntil,alerts,sessionid,paramCategories,rb,inActive,paramCount,muraTrackingID,m00000000000000000000000000000000004,m00000000000000000000000000000000000,MODULEID,timecreated,loginAttempts,siteid,DATEKEY,membersOnly,LOCALEHASDAYPARTS,copyAll,urltoken,openSectionList,muraSessionID,lastvisit,cftoken)

Code:0

Type:expression

lucee.runtime.exp.ExpressionException: key [getDefaults] doesn't exist (existing keys:visitorStatus,keywords,rememberMe,copySiteID,cfid,flatViewArgs,m00000000000000000000000000000000003,mura,paramGroups,dashboardSpan,LOCALE,SITEARRAY,paramCircuit,copyContentID,DATEKEYFORMAT,paramArray,USERFILESPATH,m00000000000000000000000000000000099,blockLoginUntil,alerts,sessionid,paramCategories,rb,inActive,paramCount,muraTrackingID,m00000000000000000000000000000000004,m00000000000000000000000000000000000,MODULEID,timecreated,loginAttempts,siteid,DATEKEY,membersOnly,LOCALEHASDAYPARTS,copyAll,urltoken,openSectionList,muraSessionID,lastvisit,cftoken)
	at lucee.commons.collection.AbstractMapPro.invalidKey(AbstractMapPro.java:803)
	at lucee.commons.collection.concurrent.ConcurrentHashMapPro$Segment.getE(ConcurrentHashMapPro.java:392)
	at lucee.commons.collection.concurrent.ConcurrentHashMapPro.g(ConcurrentHashMapPro.java:894)
	at lucee.runtime.type.scope.storage.IKStorageScopeSupport.get(IKStorageScopeSupport.java:327)
	at lucee.runtime.type.util.StructSupport.get(StructSupport.java:244)
	at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:263)
	at lucee.runtime.util.VariableUtilImpl.getCollection(VariableUtilImpl.java:257)
	at lucee.runtime.PageContextImpl.getCollection(PageContextImpl.java:1496)
	at content.contentgatewayadobe_cfc$cf.udfDefaultValue2(/mura/content/contentGatewayAdobe.cfc:1068)
	at content.contentgatewayadobe_cfc$cf.udfDefaultValue(/mura/content/contentGatewayAdobe.cfc)
	at lucee.runtime.type.UDFImpl.getDefaultValue(UDFImpl.java:504)
	at lucee.runtime.type.UDFImpl.defineArguments(UDFImpl.java:171)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:355)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:659)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2014)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at content.contentmanager_cfc$cf.udfCall2(/mura/content/contentManager.cfc:290)
	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:812)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at content.contentmanager_cfc$cf.udfCalla(/mura/content/contentManager.cfc:2983)
	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:659)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2014)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1737)
	at admin.common.layouts.includes.header_cfm$cf.call(/muraWRM/admin/common/layouts/includes/header.cfm:148)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:901)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:805)
	at admin.common.layouts.template_cfm$cf.call(/muraWRM/admin/common/layouts/template.cfm:278)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:901)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:805)
	at admin.common.layouts.default_cfm$cf.call(/muraWRM/admin/common/layouts/default.cfm:4)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:901)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:805)
	at admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1512)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:803)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:556)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:657)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:438)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
	at lucee.runtime.listener.ModernAppListener.onRequest(ModernAppListener.java:103)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2464)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2454)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2427)
	at lucee.runtime.engine.Request.exe(Request.java:44)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1090)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1038)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Column: 0
ID: ??
Line: 1068
Raw Trace: content.contentgatewayadobe_cfc$cf.udfDefaultValue2(/mura/content/contentGatewayAdobe.cfc:1068)
Template: /var/www/mysitehere/core/mura/content/contentGatewayAdobe.cfc
Type: cfml

Column: 0
ID: ??
Line: 290
Raw Trace: content.contentmanager_cfc$cf.udfCall2(/mura/content/contentManager.cfc:290)
Template: /var/www/mysitehere/core/mura/content/contentManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 2983
Raw Trace: content.contentmanager_cfc$cf.udfCalla(/mura/content/contentManager.cfc:2983)
Template: /var/www/mysitehere/core/mura/content/contentManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 148
Raw Trace: admin.common.layouts.includes.header_cfm$cf.call(/muraWRM/admin/common/layouts/includes/header.cfm:148)
Template: /var/www/mysitehere/admin/common/layouts/includes/header.cfm
Type: cfml

Column: 0
ID: ??
Line: 278
Raw Trace: admin.common.layouts.template_cfm$cf.call(/muraWRM/admin/common/layouts/template.cfm:278)
Template: /var/www/mysitehere/admin/common/layouts/template.cfm
Type: cfml

Column: 0
ID: ??
Line: 4
Raw Trace: admin.common.layouts.default_cfm$cf.call(/muraWRM/admin/common/layouts/default.cfm:4)
Template: /var/www/mysitehere/admin/common/layouts/default.cfm
Type: cfml

Column: 0
ID: ??
Line: 1512
Raw Trace: admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1512)
Template: /var/www/mysitehere/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 556
Raw Trace: admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:556)
Template: /var/www/mysitehere/admin/framework.cfc
Type: cfml`

**Comment by mattlevine** [comment]
Try clearing your template cache

**Comment by JonasEriksson** [comment]
You beat me to it Matt! I just figured I could restart Lucee and clear everything, which helped. 
Sorry, should have tried that first! Thank you for super fast reply in any case!

**Comment by mattlevine** [comment]
I'll take it!!!
