### ISSUE TITLE
Export content bundle throws following error when Slatwall Plugin exists

### ISSUE THREAD

**Issue by jsieber-aca** [blueriver/MuraCMS#2941]
When exporting content as a site bundle the following error is thrown when the Slatwall Plugin is also installed:

failed to lazily initialize a collection of role: SlatwallSite.attributeValues, could not initialize proxy - no Session

If I place a try catch block around the following lines in extedSet.cfc the bundle will complete successfully.

```
<cftry>
	<cfset extensionData = duplicate(variables.instance) />
	<cfset structDelete(extensionData,"errors") />
	<cfcatch >
	</cfcatch>
</cftry> 
```
Stacktrace:

coldfusion.runtime.EventHandlerException: Event handler exception. at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:315) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:480) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:153) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151) at coldfusion.CfmServlet.service(CfmServlet.java:219) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:134) at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doNext(FusionReactorRequestHandler.java:764) at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doHttpServletRequest(FusionReactorRequestHandler.java:344) at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doFusionRequest(FusionReactorRequestHandler.java:207) at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.handle(FusionReactorRequestHandler.java:801) at com.intergral.fusionreactor.j2ee.filter.FusionReactorCoreFilter.doFilter(FusionReactorCoreFilter.java:36) at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:71) at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.intergral.fusionreactor.agent.filter.FusionReactorStaticFilter.doFilter(FusionReactorStaticFilter.java:54) at com.intergral.fusionreactor.agent.pointcuts.NewFilterChainPointCut$1.invoke(NewFilterChainPointCut.java:41) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:355) at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:510) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: SlatwallSite.attributeValues, could not initialize proxy - no Session at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:575) at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:214) at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:155) at org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:278) at coldfusion.runtime.ObjectDuplicator.duplicateList(ObjectDuplicator.java:179) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:99) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2501) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.Struct.duplicate(Struct.java:210) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.ArrayUtil.Duplicate(ArrayUtil.java:96) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:90) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.Struct.duplicate(Struct.java:210) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.Struct.duplicate(Struct.java:210) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2501) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2527) at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2502) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.ArrayUtil.Duplicate(ArrayUtil.java:96) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:90) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.Struct.duplicate(Struct.java:210) at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102) at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78) at coldfusion.runtime.CFPage.Duplicate(CFPage.java:6734) at cfextendSet2ecfc2092054582$funcGETASXML.runFunction(D:\webroot\advc.org\core\mura\extend\extendSet.cfc:461) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074) at cfextendSubType2ecfc501982382$funcGETASXML.runFunction(D:\webroot\advc.org\core\mura\extend\extendSubType.cfc:930) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074) at cfextendManager2ecfc30157724$funcGETSUBTYPESASXML.runFunction(D:\webroot\advc.org\core\mura\extend\extendManager.cfc:1686) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074) at cfsettingsBundle2ecfc1665674767$funcBUNDLEPARTIALFILES.runFunction(D:\webroot\advc.org\core\mura\settings\settingsBundle.cfc:435) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464) at cfsettingsBundle2ecfc1665674767$funcBUNDLE.runFunction(D:\webroot\advc.org\core\mura\settings\settingsBundle.cfc:1772) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:464) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3019) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2994) at cfcarch2ecfc1639997107$funcEXPORTCONTENT.runFunction(D:\webroot\advc.org\admin\core\controllers\carch.cfc:128) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:464) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3019) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2994) at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:477) at cfframework2ecfc555034861$funcDOCONTROLLER.runFunction(D:\webroot\advc.org\admin\framework.cfc:1308) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3542) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3522) at cfframework2ecfc555034861$funcONREQUEST.runFunction(D:\webroot\advc.org\admin\framework.cfc:517) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409) at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114) at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:307) ... 58 more

**Comment by jsieber-aca** [comment]
That works on my end. Thanks!
