### ISSUE TITLE
Cannot see data anymore from some forms

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2945]
Using Mura 7.1.294.
A Mura site admin warned me that he was unable to see a form data after changing a field validation. When I look at the "form data" form, I see only "`~`" in "keyword search" instead of the field names, and I don't get any value when I click on "View data".
I found that this is caused by the value "`~`" in `tcontent.responseDisplayFields`. Looking at other entries with the same value, I found that we actually have several forms with the same issue. Some of these are old, one of them was only created a year ago.
I do not know what this value means, but I noticed other forms that have `null` instead display correctly (I think the field names are extracted from `tformresponsequestions.formField` in this case).

**Comment by damien-git** [comment]
I think this bug was introduced by [this commit](https://github.com/blueriver/MuraCMS/commit/e71892e8fbe5888eb2881a344fcc7e7e61b13044#diff-bd9a6fffe197c3488a58b467cc73c3b5).

In `dataCollectionManager.getCurrentFieldList()`, it reads the form fields from `tcontent` instead of `tformresponsequestions`. I think Mura was supposed to get the field names from `tformresponsequestions` when `tcontent.responseDisplayFields = "~"`.

In [dsp_response.cfm](https://github.com/blueriver/MuraCMS/blob/7.1/admin/core/views/carch/data_manager/dsp_response.cfm), the field names are directly extracted from `responseDisplayFields` unless it is empty or "~". Otherwise `getCurrentFieldList()` is used, which is supposed to get the names from `tformresponsequestions`.

**Comment by damien-git** [comment]
The "potential fix" fixed the issue. I think we can close it.

**Comment by damien-git** [comment]
Actually, the same user reported another issue with the same form:

> At first, the form shows all the available fields. I selected six to do a quick test.
I went back to "Edit Display," to add the remaining fields, but only the six fields I selected the first time are available (screenshot). Everything else disappeared. 
In the past, I always could see all available fields, however many times I edited the display.

**Comment by houwat** [comment]
Hi, I wanted to follow up on this issue. In essence, I can select from all available Form Data fields the first time I access a form. But, I cannot edit the display further, and I am limited to whatever fields I selected the first time around.

It would be great if we can fix that bug soon. In our case, we are in the midst of the university application season, and our faculty need access to all the data to make recruitment decisions.

Thank you.

**Comment by mattlevine** [comment]
Please update and retest

**Comment by damien-git** [comment]
We updated our dev server to 7.1.316. We're getting this error when looking at data, for all forms:


500 Error
Element FORMFIELD is undefined in RS.
Type:Expression

coldfusion.runtime.UndefinedElementException: Element FORMFIELD is undefined in RS.

	at coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:109)

	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1664)

	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1843)

	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1836)

	at cfdataCollectionManager2ecfc390152459$funcGETCURRENTFIELDLIST.runFunction(E:\web-files\devmura7\core\mura\content\dataCollection\dataCollectionManager.cfc:235)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)

	at cfdatamanager2ecfm968750628.runPage(E:\web-files\devmura7\admin\core\views\carch\datamanager.cfm:130)

	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)

	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)

	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)

	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)

	at cfframework2ecfc1917518681$funcINTERNALVIEW.runFunction(E:\web-files\devmura7\admin\framework.cfc:1538)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)

	at cfframework2ecfc1917518681$funcONREQUEST.runFunction(E:\web-files\devmura7\admin\framework.cfc:548)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)

	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)

	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)

	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)

	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)

	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)

	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)

	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)

	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:470)

	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)

	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)

	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)

	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)

	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)

	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)

	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)

	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)

	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)

	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)

	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)

	at coldfusion.CfmServlet.service(CfmServlet.java:219)

	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)

	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:458)

	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)

	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Unknown Source)


Column: 0
ID: CF_DOTRESOLVER
Line: 235
Raw Trace: at cfdataCollectionManager2ecfc390152459$funcGETCURRENTFIELDLIST.runFunction(E:\web-files\devmura7\core\mura\content\dataCollection\dataCollectionManager.cfc:235)
Template: E:\web-files\devmura7\core\mura\content\dataCollection\dataCollectionManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 130
Raw Trace: at cfdatamanager2ecfm968750628.runPage(E:\web-files\devmura7\admin\core\views\carch\datamanager.cfm:130)
Template: E:\web-files\devmura7\admin\core\views\carch\datamanager.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 1538
Raw Trace: at cfframework2ecfc1917518681$funcINTERNALVIEW.runFunction(E:\web-files\devmura7\admin\framework.cfc:1538)
Template: E:\web-files\devmura7\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 548
Raw Trace: at cfframework2ecfc1917518681$funcONREQUEST.runFunction(E:\web-files\devmura7\admin\framework.cfc:548)
Template: E:\web-files\devmura7\admin\framework.cfc
Type: CFML

**Comment by mattlevine** [comment]
https://github.com/blueriver/MuraCMS/commit/9747516cb8c39942485693ff863318ce98db07b6#diff-bd9a6fffe197c3488a58b467cc73c3b5

**Comment by damien-git** [comment]
We did an update and I am seeing all fields now. But there were 2 errors during the update:

``
Dec 10, 2018 09:45:10 AM Information [ajp-bio-8014-exec-136] - {""Suppressed"":[],""Locale"":null,""Type"":""Database"",""Sql"":""\n\t\t\t\t\tALTER TABLE tformresponsequestions\n\t\t\t\t\t\tADD CONSTRAINT pk_tformresponsequestions PRIMARY KEY (responseID,formID,formfield)\n\t\t\t\t"",""SQLState"":""HY000"",""Exceptions"":[{""message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tformresponsequestions'."",""class"":""java.sql.SQLException""},{""message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Could not create constraint or index. See previous errors."",""class"":""java.sql.SQLException""}],""queryError"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tformresponsequestions'."",""RootCause"":{""Cause"":null,""SQLState"":""HY000"",""Message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tformresponsequestions'."",""LocalizedMessage"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tformresponsequestions'."",""StackTrace"":
``

``
Dec 10, 2018 09:45:10 AM Information [ajp-bio-8014-exec-136] - {""Suppressed"":[],""Locale"":null,""Type"":""Database"",""Sql"":""\n\t\t\t\t\tALTER TABLE tpermissions\n\t\t\t\t\t\tADD CONSTRAINT pk_tpermissions PRIMARY KEY (ContentID,GroupID,SiteID,Type)\n\t\t\t\t"",""SQLState"":""HY000"",""Exceptions"":[{""message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tpermissions'."",""class"":""java.sql.SQLException""},{""message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Could not create constraint or index. See previous errors."",""class"":""java.sql.SQLException""}],""queryError"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tpermissions'."",""RootCause"":{""Cause"":null,""SQLState"":""HY000"",""Message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tpermissions'."",""LocalizedMessage"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tpermissions'."",""StackTrace"":
``

**Comment by mattlevine** [comment]
Try manually commenting out this line of code

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/dbUpdates/7.1.cfm#L16-L20

**Comment by mattlevine** [comment]
Is there error happening in the main request thread and being rendered to users or are you just seeing it in the logs? 

Also, can you also try manually editing your database's tformresponsequestions to make sure that responseID, formID, formfield are all not nullable and then re-enable the previously commented out line in the dbUpdates/7.1.cfm and do a ?appreload&applydbupdates and see if the error persists

**Comment by damien-git** [comment]
It's updated to 7.1.320, so I don't think I could try again. The error is only showing in the logs. I'm guessing it was caught and the update continued normally, just without the new keys for tformresponsequestions and tpermissions.

**Comment by damien-git** [comment]
I checked these fields are nullable. I guess you could just create a new update that fixes that and reapplies the keys.
```
name        default  nullable  type           length  indexed
----------  -------  --------  -------------  ------  -------
formField   null     YES       nvarchar(255)  510     NO     
formID      null     YES       char(35)       35      NO     
formValue   null     YES       nvarchar(-1)   -1      NO     
pollValue   null     YES       nvarchar(255)  510     NO     
responseID  null     YES       char(35)       35      NO     

```

**Comment by mattlevine** [comment]
Can't you update those to be not nullable?  New installs don't have this problem and I'm nervous that any update I'd make would cause problems for others.

**Comment by damien-git** [comment]
Sure, I could do that. But won't that be an issue for other people who updated from 7.0 ? Or did it come from Mura 6 ?

**Comment by mattlevine** [comment]
There really is no issue except a record in the logs let us know it didn't work.  I guess the for UI may be slower without that index, but nothing is broken.   So you could also just ignore it.

**Comment by damien-git** [comment]
I ended up ignoring it for now. I am closing this github issue because the initial issue is resolved.
