### ISSUE TITLE
Mura ORM getFeed: random "bean not found" error after a reload

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2946]
This issue happens randomly, about 1 in 5 times, after a Mura reload. The reload can happen because of a change of site settings, changing the plugins or with a manual reload - the issue can happen in all these cases.
A plugin using Mura ORM calls `getFeed` on some requests (in `onSiteRequestStart`). It fails with a "bean not found" error. If it starts failing, it keeps failing afterwards. If it succeeds after a reload, it always succeeds afterwards. The beans are registered with `registerBeanDir` in `onApplicationLoad`.

The plugin source is available at [https://github.com/MSU-NatSci/MuraRedirect](https://github.com/MSU-NatSci/MuraRedirect).

Using IIS 10, Adobe CF 11.0.15, Mura 7.1.309.

**Comment by damien-git** [comment]
Here is a stack trace (this was before I started catching these exceptions, so line numbers might be a little bit off; also the Mura version was a bit older). The same error happens with other plugins.

Sep 5, 2018 10:05:10 AM Error [ajp-bio-8014-exec-252] - coldfusion.runtime.CustomException: bean not found: redirect at
coldfusion.tagext.lang.ThrowTag.doStartTag(ThrowTag.java:142) at
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000) at
cfioc2ecfc913303805$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\bean\ioc.cfc:136) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at
cfcfobject2ecfc52254188$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\cfobject.cfc:104) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2503) at
cfMuraScope2ecfc884289064$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\MuraScope.cfc:361) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854) at
cfMuraScope2ecfc884289064$funcGETFEED.runFunction(E:\web-files\mura7\core\mura\MuraScope.cfc:551) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at
cfredirectMgt2ecfc2078899840$funcGETREDIRECTURL.runFunction(E:\web-files\mura7\plugins\MuraRedirect\model\redirectMgt.cfc:259) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at
cfeventHandler2ecfc1506488583$funcONSITEREQUESTSTART.runFunction(E:\web-files\mura7\plugins\MuraRedirect\model\handlers\eventHandler.cfc:23) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424) at
coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:406) at
cfpluginManager2ecfc976971741$funcEXECUTESCRIPTS.runFunction(E:\web-files\mura7\core\mura\plugin\pluginManager.cfc:1728) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533) at
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819) at
cfpluginManager2ecfc976971741$funcANNOUNCEEVENT.runFunction(E:\web-files\mura7\core\mura\plugin\pluginManager.cfc:1270) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at
cfcontentServer2ecfc1974689196$funcDOREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:779) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854) at
cfcontentServer2ecfc1974689196$funcPARSEURL.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:257) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854) at
cfcontentServer2ecfc1974689196$funcPARSEURLROOT.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:343) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424) at
cfcontentServer2ecfc1974689196$funcHANDLEROOTREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:707) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at
cfindex2ecfm1842569852.runPage(E:\web-files\mura7\index.cfm:32) at
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246) at
coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736) at
coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572) at
coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) at
coldfusion.filter.IpFilter.invoke(IpFilter.java:45) at
coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:474) at
coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42) at
coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at
coldfusion.filter.PathFilter.invoke(PathFilter.java:153) at
coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) at
coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at
coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at
coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58) at
coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at
coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at
coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at
coldfusion.CfmServlet.service(CfmServlet.java:219) at
coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at
coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at
coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:466) at
org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197) at
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) at
org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) at
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at
java.lang.Thread.run(Unknown Source)

**Comment by damien-git** [comment]
Here is a more recent stack trace. This one happened with [Mura Social Wall](https://github.com/MSU-NatSci/MuraSocialWall). The redirect plugin failed on the same reload, so I suspect all Mura ORM fails at the same time on a reload. Maybe an issue with `variables.discoveryComplete` ?


"Error","ajp-bio-8014-exec-3","11/20/18","14:39:24","MURAA950E194C8DE7594A2F2DD0F08A4BAE2","coldfusion.runtime.CustomException: bean not found: socialwallconfig  	at coldfusion.tagext.lang.ThrowTag.doStartTag(ThrowTag.java:142)  	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)  	at cfioc2ecfc913303805$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\bean\ioc.cfc:136)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)  	at cfcfobject2ecfc52254188$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\cfobject.cfc:104)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2503)  	at cfMuraScope2ecfc884289064$funcGETBEAN.runFunction(E:\web-files\mura7\core\mura\MuraScope.cfc:361)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)  	at cfindex2ecfm1603210473._factor0(E:\web-files\mura7\plugins\MuraSocialWall\display_objects\social_wall\index.cfm:7)  	at cfindex2ecfm1603210473._factor4(E:\web-files\mura7\plugins\MuraSocialWall\display_objects\social_wall\index.cfm:2)  	at cfindex2ecfm1603210473.runPage(E:\web-files\mura7\plugins\MuraSocialWall\display_objects\social_wall\index.cfm:1)  	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)  	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)  	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)  	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)  	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT_INCLUDE.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:1605)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)  	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT_RENDER.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:1520)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)  	at cfcontentRendererUtility2ecfc1543563231$funcDSPOBJECT.runFunction(E:\web-files\mura7\core\mura\content\contentRendererUtility.cfc:1285)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)  	at cfcontentRenderer2ecfc2053238892$funcDSPOBJECT.runFunction(E:\web-files\mura7\core\mura\content\contentRenderer.cfc:2354)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819)  	at cfcfobject2ecfc52254188$funcINVOKEMETHOD.runFunction(E:\web-files\mura7\core\mura\cfobject.cfc:225)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)  	at cfMuraScope2ecfc884289064$funcONMISSINGMETHOD.runFunction(E:\web-files\mura7\core\mura\MuraScope.cfc:103)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:291)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:664)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)  	at cfapiUtility2ecfc1747204565$funcPROCESSASYNCOBJECT.runFunction(E:\web-files\mura7\core\mura\client\api\json\v1\apiUtility.cfc:3387)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819)  	at Statement58.evaluate(<generated>:1)  	at coldfusion.compiler.ExprClassLoader.evaluate(ExprClassLoader.java:149)  	at coldfusion.runtime.CFPage.Evaluate(CFPage.java:2326)  	at cfapiUtility2ecfc1747204565$funcPROCESSREQUEST.runFunction(E:\web-files\mura7\core\mura\client\api\json\v1\apiUtility.cfc:860)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)  	at cfcontentServer2ecfc1974689196$funcHANDLEAPIREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:559)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)  	at cfcontentServer2ecfc1974689196$funcHANDLEROOTREQUEST.runFunction(E:\web-files\mura7\core\mura\content\contentServer.cfc:698)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)  	at cfindex2ecfm1842569852.runPage(E:\web-files\mura7\index.cfm:43)  	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)  	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)  	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)  	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)  	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)  	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:474)  	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)  	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)  	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)  	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)  	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)  	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)  	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)  	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)  	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)  	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)  	at coldfusion.CfmServlet.service(CfmServlet.java:219)  	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)  	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)  	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)  	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)  	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)  	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)  	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)  	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)  	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)  	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)  	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)  	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)  	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)  	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:458)  	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)  	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)  	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)  	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)  	at java.lang.Thread.run(Unknown Source)  "

**Comment by mattlevine** [comment]
If you look in your logs can you tell if an error may be happening during the application loads where it doesn't get wired up?

I actually recently made an update to fix an issue where then plugins would fail with debuggingEnabled set to false it would silently fail without even a logged event

https://github.com/blueriver/MuraCMS/commit/26dc867a83f5e67cd298ce68302f998f3c8d1437#diff-14021844d15533bf5433b2b53f66e65a

Now they will get logged.

**Comment by damien-git** [comment]
No, I didn't see any other error in the logs. It is possible that this issue is related to the large number of sites we have in one instance, but I don't have any lead... Also, I forgot to mention earlier that the DBMS is SQL Server.

**Comment by mattlevine** [comment]
Just to clarify, my point about the logged errors was that they would not be logged until you updated to get that commit I referenced.  Do you have that patch in place?

**Comment by damien-git** [comment]
Yes, we have Mura 7.1.309.
I added some writeLog in the plugin to make sure registerBeanDir is called, and called before the error happens. We'll see if anything interesting comes up.

**Comment by damien-git** [comment]
I found that onApplicationLoad had been called twice the last time this issue happened. I don't know what happens if registerBeanDir is called twice, but maybe this is where it's coming from.
