### ISSUE TITLE
Category_summary error on edit

### ISSUE THREAD

**Issue by svlacic** [blueriver/MuraCMS#2948]
While in inline editor, you can add category summary to page and it works fine. If you click on pencil icon in order to edit it you get an error. 

Just upgraded to v7.1. I removed my customizations, tried on default site and it gives me always the same error. I am on CF11 update 15. Error is below:

Nov 21, 2018 08:22:27 AM Error [ajp-bio-8014-exec-4] - coldfusion.runtime.EventHandlerException: Event handler exception.  	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:309)  	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:470)  	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)  	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)  	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)  	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)  	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)  	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)  	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)  	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)  	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)  	at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)  	at coldfusion.CfmServlet.service(CfmServlet.java:219)  	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)  	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)  	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)  	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)  	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)  	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)  	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)  	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:134)  	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doNext(FusionReactorRequestHandler.java:755)  	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doHttpServletRequest(FusionReactorRequestHandler.java:344)  	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doFusionRequest(FusionReactorRequestHandler.java:207)  	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.handle(FusionReactorRequestHandler.java:792)  	at com.intergral.fusionreactor.j2ee.filter.FusionReactorCoreFilter.doFilter(FusionReactorCoreFilter.java:36)  	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:71)  	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at com.intergral.fusionreactor.agent.filter.FusionReactorStaticFilter.doFilter(FusionReactorStaticFilter.java:54)  	at com.intergral.fusionreactor.agent.pointcuts.NewFilterChainPointCut$1.invoke(NewFilterChainPointCut.java:41)  	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java)  	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)  	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)  	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)  	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)  	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)  	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)  	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:458)  	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)  	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)  	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)  	at java.lang.Thread.run(Thread.java:748)  Caused by: coldfusion.runtime.UndefinedElementException: Element navigation is undefined in a CFML structure referenced as part of an expression.  	at coldfusion.runtime.CfJspPage.ArrayGetAt(CfJspPage.java:972)  	at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:983)  	at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:978)  	at cfsettingsBean2ecfc510475060$funcGETDISPLAYOBJECT.runFunction(C:\website\core\mura\settings\settingsBean.cfc:1980)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)  	at cfloadclassconfigurator2ecfm943282557.runPage(C:\website\admin\core\views\carch\loadclassconfigurator.cfm:112)  	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)  	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)  	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)  	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)  	at cfframework2ecfc1787488828$funcINTERNALVIEW.runFunction(C:\website\admin\framework.cfc:1538)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)  	at cfframework2ecfc1787488828$funcONREQUEST.runFunction(C:\website\admin\framework.cfc:548)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)  	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)  	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)  	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)  	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)  	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)  	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)  	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:301)  	... 52 more

**Comment by svlacic** [comment]
I tested it with your fix and everything is working now. Slaven
