### ISSUE TITLE
Mura 7.1 Update Core error

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2958]
Hi, I just hit update core on a Mura 7.1.x (fairly recent, perhaps two weeks old core) and now get this error which shows on public and admin pages (I'll try and move over the core directory manually now, perhaps that works. This is on Lucee, so not sure what "Adobe" stuff is causing this.

`500 Error
key [RSHIST] doesn't exist in argument scope. existing keys are [topID, siteid]
Code:0
Type:expression
lucee.runtime.exp.ExpressionException: key [RSHIST] doesn't exist in argument scope. existing keys are [topID, siteid]
	at lucee.runtime.type.scope.ArgumentImpl.get(ArgumentImpl.java:152)
	at content.contentgatewayadobe_cfc$cf.udfCall3(/mura/content/contentGatewayAdobe.cfc:1529)
	at content.contentgatewayadobe_cfc$cf.udfCall(/mura/content/contentGatewayAdobe.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:657)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at content.contentmanager_cfc$cf.udfCall1(/mura/content/contentManager.cfc:207)
	at content.contentmanager_cfc$cf.udfCall(/mura/content/contentManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:657)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at admin.core.controllers.carch_cfc$cf.udfCall1(/muraWRM/admin/core/controllers/carch.cfc:210)
	at admin.core.controllers.carch_cfc$cf.udfCall(/muraWRM/admin/core/controllers/carch.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:659)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2010)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at admin.framework_cfc$cf.udfCall6(/admin/framework.cfc:1308)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:803)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:517)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:657)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:438)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
	at lucee.runtime.listener.ModernAppListener.onRequest(ModernAppListener.java:103)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2464)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2454)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2427)
	at lucee.runtime.engine.Request.exe(Request.java:44)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1090)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1038)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Column: 0
ID: ??
Line: 1529
Raw Trace: content.contentgatewayadobe_cfc$cf.udfCall3(/mura/content/contentGatewayAdobe.cfc:1529)`

**Comment by mattlevine** [comment]
Try clearing you component cache and reloading Mura

**Comment by JonasEriksson** [comment]
@mattlevine - I am sorry - you helped me with I think the same issue about a month ago - your suggestion solved it! I am going to put a sticky tape on my second monitor saying: "Clear Component Cache after Mura Core Update" now so hopefully I don't forget it in the future! :-) Thanks again!
