### ISSUE TITLE
Error parsing JSON string

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2984]
We are getting these exceptions frequently since updating Mura to 7.1.396. I do not know if it affects user experience.

```
"Error","ajp-bio-8014-exec-199","03/15/19","13:15:06",,"Error parsing JSON string"
java.lang.NumberFormatException: For input string: "-"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at java.lang.Double.valueOf(Unknown Source)
	at coldfusion.runtime.JSONUtils.parseNumber(JSONUtils.java:1939)
	at coldfusion.runtime.JSONUtils.parseObject(JSONUtils.java:1523)
	at coldfusion.runtime.JSONUtils.parseJSON(JSONUtils.java:1443)
	at coldfusion.runtime.JSONUtils.deserializeJSON(JSONUtils.java:308)
	at coldfusion.runtime.JSONUtils.deserializeJSON(JSONUtils.java:249)
	at coldfusion.runtime.CFPage.DeserializeJSON(CFPage.java:8203)
	at cfPortcullis2ecfc490862422$funcSTRIPMSWORD.runFunction(E:\web-files\mura7\core\mura\Portcullis.cfc:374)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2865)
	at cfPortcullis2ecfc490862422$funcFILTERTAGS.runFunction(E:\web-files\mura7\core\mura\Portcullis.cfc:402)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2865)
	at cfPortcullis2ecfc490862422$funcSCAN.runFunction(E:\web-files\mura7\core\mura\Portcullis.cfc:151)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:651)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:460)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2430)
	at cfscriptProtect_include2ecfm827105190.runPage(E:\web-files\mura7\core\appcfc\scriptProtect_include.cfm:38)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:247)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3011)
	at cfonRequestStart_scriptProtect_method2ecfm178609781$funcONREQUESTSTART.runFunction(E:\web-files\mura7\core\appcfc\onRequestStart_scriptProtect_method.cfm:48)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:646)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:435)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:405)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:463)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:458)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mattlevine** [comment]
Please update and let re-open this ticket if the issue persists.  It's present differently though.

**Comment by damien-git** [comment]
I am still having the same error after updating Portcullis.cfc (now at Portcullis.cfc:375). It looks like the cftry / cfcatch is not catching the exception... This is with CF11.

**Comment by mattlevine** [comment]
Has anyone seen this in CF2016+?   I'll ponder what i can do, perhaps just conditionally not run this code for CF11.  However, one thing I would point out is that CF11 will no longer be supported by Adobe next month.  So you should look into upgrading.

https://www.carehart.org/blog/client/index.cfm/2018/12/20/CF11_countdown_clock_is_ticking

**Comment by damien-git** [comment]
related ColdFusion bug: https://tracker.adobe.com/#/view/CF-4204079
(this CF bug is known to affect CF10, CF11, CF2016 and CF2018)

**Comment by damien-git** [comment]
This bug could be fixed by editing line 373 of `core/mura/Portcullis.cfc`:
    replace
      `<cfelseif isJson(arguments.value)>`
    by
      `<cfelseif isJson(arguments.value) && arguments.value neq '-'>`
