### ISSUE TITLE
The method 'passwordsExpire' is not defined

### ISSUE THREAD

**Issue by blueMonkeyDelft** [blueriver/MuraCMS#3187]
Since we upgraded to 7.1.501 we get this error when "add" or "edit" a User

500 Error
The method 'passwordsExpire' is not defined
Type:application
lucee.runtime.exp.CustomTypeException: The method 'passwordsExpire' is not defined
	at lucee.runtime.tag.Throw._doStartTag(Throw.java:212)
	at lucee.runtime.tag.Throw.doStartTag(Throw.java:201)
	at configbean_cfc$cf.udfCall1(/mura/configBean.cfc:219)
	at configbean_cfc$cf.udfCall(/mura/configBean.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:614)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at admin.core.views.cusers.edituser_cfm$cf.call(/muraWRM/admin/core/views/cusers/edituser.cfm:190)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:933)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:805)
	at admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1538)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:803)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:548)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:357)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:573)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1997)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:438)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2464)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2454)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2427)
	at lucee.runtime.engine.Request.exe(Request.java:44)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1090)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1038)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1225)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:684)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2527)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2516)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Column: 0
ID: ??
Line: 219
Raw Trace: configbean_cfc$cf.udfCall1(/mura/configBean.cfc:219)
Template: /var/www/core/mura/configBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 190
Raw Trace: admin.core.views.cusers.edituser_cfm$cf.call(/muraWRM/admin/core/views/cusers/edituser.cfm:190)
Template: /var/www/admin/core/views/cusers/edituser.cfm
Type: cfml

Column: 0
ID: ??
Line: 1538
Raw Trace: admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1538)
Template: /var/www/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 548
Raw Trace: admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:548)
Template: /var/www/admin/framework.cfc
Type: cfml

**Comment by randriese** [comment]
This issue is resolved in 7.1.502
